### ISSUE TITLE
Advanced Writer cannot edit own published articles

### ISSUE THREAD

**Issue by AgaritaBerry** [worldanvil/worldanvil-bug-tracker#1042]
**Michael Chandra / Iffygeneia**:

**Mysthaven **:

**Advanced Writer**: 

**Describe the Issue**
I have given several friends Advanced Writer privileges on a shared world, but when one of them published a draft, she no longer could access it. We had to set it back to Draft so she could edit it again. She's still the official author of the article, so according to the documentation, as Advanced Writer she should have edit-rights to it.

**To Reproduce**
1. Create an article as Advanced Writer
2. Publish it
3. Be blocked from seeing and editing it

**Expected behavior**
Advanced writers should be able to see+edit articles they are the author of, even if it's published.

**Screenshots**
![image](https://user-images.githubusercontent.com/80285999/168909292-3ea55340-fa17-4a4f-a769-2f1f1fecce8d.png)
![image](https://user-images.githubusercontent.com/80285999/168909311-bdd8b00f-08da-400a-b856-05b1950413b0.png)

**Comment by iamromeo** [comment]
The Advanced writer feature is designed under the principle that a writer that does not have full access to the project may be tasked to create an article and hold the ability to edit it while this article is a draft. That means that once approved they no longer have access to edit it. 

That allows world owners to protect their world from writers that came in to work on something (because they were commissioned or otherwise contracted) and then - although - they keep can the keep the IP of their document, they cannot modify it. 

This is not a bug, this was simply, designed with a different purpose in mind.

**Comment by iamromeo** [comment]
updatae: I will need to go back to my notes and re-examine this. Added to the queue
