### ISSUE TITLE
World Anvil Character Creation

### ISSUE THREAD

**Issue by LiminalityofRain** [worldanvil/worldanvil-bug-tracker#1068]
When I attempt to create a new character (World and Heroes --> switch to ... --> +New Character), the screen tries to load sideways instead of vertically. See the screenshot. That is the entire screen - it cannot be expanded, and there is no way to scroll to the side. 

I cannot continue with character creation or save even my character's name. It seems to be loading the pieces of the character creator incorrectly. I am using a desktop computer (I have also tried this on my Chromebook and had the same issue) Google Chrome as my web browser: Chrome is up to date Version 102.0.5005.63 (Official Build) (64-bit).

Edit: It may be important to note that this would be my SECOND character. I have one character already and am attempting to create a second one for a different campaign. 

![WorldAnvilNewCharacter](https://user-images.githubusercontent.com/106878461/172011280-41cfcc67-6ef2-4da1-982c-c6f753d77468.PNG)

**Comment by Kordishal** [comment]
Hi! This is a visual glitch with the page adding the form fields next to each other instead of top of each other. This is not something that happens in general and I am unable to reproduce it with the information given.

The number of characters wouldn't affect this layout.

It could be that this is caused by some kind of extension you have installed on both your devices. Otherwise I am not sure. You should check this page using a private / incognito window in Chrome and potentially in different browsers to see if the issue persists there.

**Comment by iamromeo** [comment]
I cannot reproduce this - probably an issue wiht a local plugin but there is nothing on this page that can cause this.
