### ISSUE TITLE
Generate Articles Metadata Table

### ISSUE THREAD

**Issue by MGatta** [worldanvil/worldanvil-bug-tracker#1070]
**World Anvil Username**: MGatta

**Feature**: @Kordishal's Generate Articles Metadata Table

**Describe the Issue**
I requested a complete metadata table of my world and I got an error:
"Job failed: rq.timeouts.JobTimeoutException: Task exceeded maximum timeout value (180 seconds)"

**Expected behavior**
To be able to obtain the metadata without an error.

**Comment by iamromeo** [comment]
@Kordishal can you elaborate on this?

**Comment by Kordishal** [comment]
@iamromeo The job has a time limit at 3 minutes. It takes a long time to extract a 500+ articles from the API because I have to call each and everyone of them.

I haven't increased the limit, because it should be long enough and was hoping the improvements to the API will allow me to get this data much faster in the future

**Comment by iamromeo** [comment]
I do not forsee that happening - at this point there are no plans to make the full article read faster - and honestly I am not sure where we'd start for something like that.
