### ISSUE TITLE
Moving grouped objects with grid enabled disrupts internal group alignment

### ISSUE THREAD

**Issue by xaqaria** [worldanvil/worldanvil-bug-tracker#1072]
**World Anvil Username**:  Xaqaria

**World / Campaign / RPG Character / Manuscript Title**: Earth I Guess

**Feature**: Whiteboards

**Related URLS** (To public & visible pages add screenshots otherwise):
<img width="447" alt="image" src="https://user-images.githubusercontent.com/4044089/172442253-fafbc4aa-ee7b-4ecd-b6f2-d6075b64da1f.png">

**Describe the Issue**
When editing a whiteboard with the GRID turned on, grouped objects will individually align to grid instead of the group as a whole.

**To Reproduce**
1. Create object 1 (e.g. Circle)
2. Create object 2 (e.g. Square)
3. Select object 1 and 2
4. Right-click on the selection and choose Align/Distribute, Horizontal Center
5. Right-click on the selection and choose Align/Distribute, Vertical Center
6. Right-click on the selection and choose Group
7. Ensure Grid is turned **on** by selecting Menu, Preferences, Grid
8. Move the group

**Expected behavior**
Grouped objects should be aligned to the grid based on the group's bounding box.  Individual objects should be moved as an offset to the group, 

**Screenshots**
<img width="447" alt="image" src="https://user-images.githubusercontent.com/4044089/172442253-fafbc4aa-ee7b-4ecd-b6f2-d6075b64da1f.png">

**Comment by Duranzno** [comment]
Yes, this is part of the intended behavior as by default the system takes the grid alignment as more relevant when moving an object.

In order to have the desired behaviour you describe you can enable to "Toggle Aspect Ratio Lock" on the Action Menu
![image](https://user-images.githubusercontent.com/9256602/175557973-87be5b66-050a-4ddb-9e30-a7bcc1534140.png)
