### ISSUE TITLE
Spoiler block cannot be opened

### ISSUE THREAD

**Issue by J-Bot15** [worldanvil/worldanvil-bug-tracker#1076]
**World Anvil Username**: FenShui

**World / Campaign / RPG Character / Manuscript Title**: Godborn / Las Diez Obras del Forjador

**Feature**: Spoiler

**Related URLS** (To public & visible pages add screenshots otherwise): https://www.worldanvil.com/w/godborn-fenshui/a/las-diez-obras-del-forjador-item?preview=true** 

**Describe the Issue**
The spoiler feature is not working correctly, when I try to open the spoiler nothing happens, leaving the text inaccessible. I've tried using multiple web browsers and even devices and the bug is consistent across them. The weirdest thing is that only a hour ago it did work, but now I'm unable to make function again.

**Screenshots**
![image](https://user-images.githubusercontent.com/107251859/173048091-887f896c-d5ad-468c-8ae1-504140c1ae0a.png)
![image](https://user-images.githubusercontent.com/107251859/173048173-8a4d30f2-a818-49cd-8b06-74f82053164a.png)

**Comment by Kordishal** [comment]
Hi! It is not just the spoiler that is not responsive, but all elements on your article. This means that there is an invisible element that covers your page. This happens when there is an unclosed or unopened container BBCode like [center], [justify], [in] etc.

Check your code and fix it and it will start to work again!
