### ISSUE TITLE
Extra White Space Before Articles

### ISSUE THREAD

**Issue by GeekzGamingz** [worldanvil/worldanvil-bug-tracker#11]
**World Anvil Username**:
GeekzAnonymous

**Related URLS** (add URLs of the pages that do not work!):
https://www.worldanvil.com/w/GeekzAnonymous-Oryth

**Describe the bug**
There is an extra whitespace before articles that cause the text to not line up with categories. If this is intentional, whitespace cannot be targetted by CSS so I cannot customize it myself.

**Screenshots**
![Capture3](https://user-images.githubusercontent.com/42735252/109426453-c4a62480-79bb-11eb-8bc1-8b1612986f27.JPG)
![Capture4](https://user-images.githubusercontent.com/42735252/109426461-ca9c0580-79bb-11eb-94f9-d2933562d0ca.JPG)

**Comment by Xuroth** [comment]
Heya! The FontAwesome Icons and RPG Awesome Icons each have a utility class because sometimes the actual icon element's width is not standardized (some glyphs have a little more width) and the rendered element ends up breaking vertical list flow. The 'fixed width' class will often help, so if you could try the following out and see if it helps that would be awesome.

For RPG Awesome (classes with `ra`) add ` ra-fw`. Ex. `ra ra-fw ra-scroll-unfurled`
For FontAwesome (classes with `fa`, `fas`, `far`, or `fal`) add ` fa-fw`. Ex. `fas fa-fw fa-chevron-right`

Note, it would be ideal to add these classes to every icon to ensure uniformity, even the ones that "appear" to line up correctly, as the utility classes will force a standard width (that is often a little wider than the smaller icon glyphs).

See if this helps at all, and if so, let us know.

**Comment by GeekzGamingz** [comment]
To clarify: This error occurs on vanilla icons as well. There is an actual extra Whitespace HTML element in the code.
Category Example (One Whitespace):
![Capture](https://user-images.githubusercontent.com/42735252/109434035-40669800-79e1-11eb-938f-53b66e31491e.JPG)
Article Example (Two Whitespaces):
![Capture2](https://user-images.githubusercontent.com/42735252/109434044-4b212d00-79e1-11eb-830a-455740a2ac7b.JPG)
![Capture3](https://user-images.githubusercontent.com/42735252/109434045-4c525a00-79e1-11eb-9344-f89157b75fbc.JPG)
Vanilla Example (Taken from a different users world: https://www.worldanvil.com/w/Arnathia)
![Capture4](https://user-images.githubusercontent.com/42735252/109434141-c71b7500-79e1-11eb-8db4-5c3eba956e49.JPG)
![Capture5](https://user-images.githubusercontent.com/42735252/109434142-c8e53880-79e1-11eb-8094-e3e6de48faff.JPG)
![Capture6](https://user-images.githubusercontent.com/42735252/109434144-ca166580-79e1-11eb-9dbe-723c17189c32.JPG)

**Comment by iamromeo** [comment]
All done

**Comment by GeekzGamingz** [comment]
Not seeing the change.

**Comment by iamromeo** [comment]
![Screenshot 2021-03-05 at 06 45 54](https://user-images.githubusercontent.com/660175/110068467-7196ed80-7d7e-11eb-9f12-d4f9714c259d.png)

Screenshot from your world

**Comment by iamromeo** [comment]
Oh, did you mean the gap in "Meta" ? (just fixed that will deploy later today)

**Comment by Kordishal** [comment]
On the screenshot you posted, I still see two spaces on the HEXTOR & INDRTYTH articles while the RELIGIONS category does not seem to have it.
![image](https://user-images.githubusercontent.com/14262536/110086122-43bba400-7d92-11eb-8d8a-8bc11c167d3a.png)

To me it looks like that extra &nbsp; causes the issue.

**Comment by iamromeo** [comment]
You are correct- found and fix that instance as well

**Comment by GeekzGamingz** [comment]
Thank you guys so much for your hard work.
Just checked, but now there is no space at all. I can change that with CSS
on my end at least, but I still wanted to point it out to you.
[image: image.png]

**Comment by Kordishal** [comment]
Hm yeah, that was already the case on sub-articles. So I think it makes sense and as you said people can now add padding/margins to change it the way they want it to be.

**Comment by iamromeo** [comment]
@Kordishal @GeekzGamingz sorry guys - I am doing a last change here - there should be a space always between them just not two
