### ISSUE TITLE
Ordered lists rendered as unordered lists in Notebook

### ISSUE THREAD

**Issue by dprothero** [worldanvil/worldanvil-bug-tracker#1104]
**World Anvil Username**: dpro

**World / Campaign / RPG Character / Manuscript Title**: N/A (not public)

**Feature**: Notebook

**Related URLS** (To public & visible pages add screenshots otherwise): N/A

**Describe the Issue**
In the campaign notebook, if I try to do an ordered list:
 ```
 [ol]
 [li]Item 1[/li]
 [li]Item 2[/li]
 [li]Item 3[/li]
 [/ol]
 ```

And then I click the eyeball icon to view it, it doesn't render it as an ordered list with numbers:

- Item 1
- Item 2
- Item 3

**To Reproduce**
1. Go to the [Notebook](https://www.worldanvil.com/notebook/)
2. Create a note
3. Add an ordered list like so:
   ```
   [ol]
   [li]Item 1[/li]
   [li]Item 2[/li]
   [li]Item 3[/li]
   [/ol]
   ```
5. Click the eyeball icon in the upper right of the editor to preview
6. The lists are shown as bullets (2nd-level bullets at that):
    - Item 1
    - Item 2
    - Item 3

**Expected behavior**
The list should show up as a numbered list, like so:
1. Item 1
2. Item 2
3. Item 3

**Screenshots**
![image](https://user-images.githubusercontent.com/1897006/174206600-80f11055-2927-4d56-957b-387b96f4e368.png)

![image](https://user-images.githubusercontent.com/1897006/174206636-1178dc85-f177-4ebf-9009-a9e5c20da127.png)

**Comment by iamromeo** [comment]
Hey there :) 

Well that is a very odd bug - will have a look asap :)

**Comment by iamromeo** [comment]
Hey @dprothero 

I managed to replicate this when using the [li] ... [/li] structure on the notebook. but it works perfectly with the - shorthand (see below) I will investigate because it is the same code that powers both the parser for the notebook and the articles so there is something odd going on, but fo the time being the shorthand apart from being faster, also works. 

![image](https://user-images.githubusercontent.com/660175/174236048-4a50c43b-3756-49ad-9fcc-078c46228cbd.png)


![image](https://user-images.githubusercontent.com/660175/174236017-0ecfb984-04c8-4bbc-ac54-3ff172d69ddd.png)
