### ISSUE TITLE
Variety of map-making issues

### ISSUE THREAD

**Issue by Dawnfire82** [worldanvil/worldanvil-bug-tracker#111]
**Marker Menu fails to open**
As of 3/28/2021, when adding markers to a map, the selection dropdown menu for the type of marker does not open. Typing the first characters does not open it, and neither does clicking. I cannot select the pin type. If I enter the name of my desired marker type manually, it is ignored and a generic blue marker is created.

The overlay previewer still seems to work with Alt-Enter. 

![bug capture](https://user-images.githubusercontent.com/81523477/112758044-476dcf80-8fba-11eb-94cc-b309610f856e.PNG)

This always worked, before.

**Marker Popup incorrect in edit mode**
Also, when I create a generic blue marker anyway and mouse over it in edit mode, the pop-up is no longer representative. EXAMPLE: If I create a marker called "Raven's Nest," the resulting popup is "Raven&#039;s Nest". Presentation Mode still shows it correctly.

**Maps centered by screen, not available screen**
I first noticed this last week or so. When opening a map to edit, the map is centered by overall screen width, rather than by available screen (taking the right-hand marker creation window into account). On smaller maps, this means much of it is hidden and must be dragged left every single time the page is reloaded.
 
![bug capture 2](https://user-images.githubusercontent.com/81523477/112758158-d4188d80-8fba-11eb-960d-0b67e7ed8083.PNG)

My browser type is Brave 1.22.70 Chromium 89.0.4389.105 (Official Build) (64-bit).

**Comment by Kordishal** [comment]
The dropdown was replaced with a search that displays the images of the pins instead. The problem with the invisible one is of course that it is invisible, guess Dimitris forgot to make a special solution for that one. Otherwise, it works fine. 

Don't see what you mean with the second point? What is the difference? You just included a comma once and then not? I don't see any difference in the title display between editor and presentation. You'll have to elaborate on that.

The overlay is ignored yeah for where to centre yeah. Not sure if it would be really better to change that.

**Comment by iamromeo** [comment]
Hahhaha - the invisible pin is a hilarious issue - it hasn't even crossed my mind - let me see what I can do about it :) 
The rest, please let me know if there is an actual bug there @Kordishal - it's a bit unclear.

**Comment by iamromeo** [comment]
https://user-images.githubusercontent.com/660175/112786350-b8ff5980-905e-11eb-9c16-89a80fe0cc28.mov

The main issue is fixed. 
**Please make sure you post a single issue per ticket.**
