### ISSUE TITLE
Article Link Shenanigans

### ISSUE THREAD

**Issue by Dawnfire82** [worldanvil/worldanvil-bug-tracker#112]
**Linking Blank Spaces**
When linking to another article, the program does not read blank spaces. For instance, if I try to link to an article called "The Great Gate," and I enter "@The " the dropdown of options vanishes. This means I can only enter "@The" and then select from the list of all other articles which *also* begin with or include "The," which is quite a few.

**Template Specific Prompts and Connections**
When trying to link to articles in the additional template specific areas you can expand below the main article, pressing enter does nothing. For instance, if I enter "@The" and arrow down to "The Great Gate" and press enter, the result is a carriage return. The link is not created. It only links if I mouse over and click the correct article.

In main body content windows, arrowing and pressing 'enter' does create the selected article link, as intended. 

**Navigation**
When links are present in an article, navigation and manipulations with carriage returns and arrows are wonky. Arrowing will simply stop working when the cursor crosses the article link. 'Enter' adds a carriage return to the end of the paragraph, but not to the line where the cursor is. I often have to cut text out with CTRL-X and re-paste it elsewhere to create a /CR where I intend. 

Swapping over to 'Source mode' with the View Source button seems to solve navigation issues, but not the others.

**Comment by Kordishal** [comment]
The linking searches all the text. So just enter _gate_ or _great_ instead of _the_. Alternatively, space can be replaced with an underscore `_`. 

I cannot reproduce the second issue. When I press enter it always adds the selected link and not a new line (there are no carriage returns...). And it doesn't matter which editor or text area I try it in. 

The last issue is a known issue with the Plato editor and will not be fixed before the rework (which has no specific ETA). Switch to the [Euclid](https://www.worldanvil.com/w/WorldAnvilCodex/a/text-editors) editor to avoid these issues.

And in the future please create a separate issue for each issue. It is harder to triage them otherwise.
