### ISSUE TITLE
Timeline in Chronicle not displaying events

### ISSUE THREAD

**Issue by Fornaxus** [worldanvil/worldanvil-bug-tracker#1126]
**World Anvil Username**: Fornaxus

**World / Campaign / RPG Character / Manuscript Title**: Emrath

**Feature**: Chronicle

**Related URLS** (To public & visible pages add screenshots otherwise): N/A

**Describe the Issue**
With the exception of the very first event I created for the Chronicle, none of the events I've created are showing up on the timeline, although they do show up when using the Events Manager, so the events definitely exist.

**To Reproduce**
Create an event, complete with color of bar and icon from RPGAwesome (as recommended in the app)
No event bar displays on the timeline, despite re-loading the page.

**Expected behavior**
An event bar should show up on the timeline.

**Screenshots**
![image](https://user-images.githubusercontent.com/108236680/175829573-9c0d654e-8023-42ea-a164-3ec5d19cd15f.png)

**Comment by Kordishal** [comment]
Hi, I assume you mean the chronicle and not a campaign since the screenshot is of a chronicle and campaigns do not have timelines. I updated your report to reflect that.

As for the actual issue: I cannot reproduce this or make it happen with what you have posted.

Have you checked the events show up in the event manager and that they have the correct date that you wanted? 
Have you tried doing this on a different browser? Different device?
Add any other information that might help to track this issue down. Like what RPG Awesome icon are you using? What colour are you using?

**Comment by Fornaxus** [comment]
Hey, Jonas, thanks for the quick reply.
Thanks for the correction. I suppose it's a good thing I included a screenshot. 
Events with start time only are still not showing up, but after I restarted my computer, the events with both a start and and end date do. Even when I shorten the time granularity to days instead of years, it still doesn't display anything that shows where that instantaneous event took place (although hovering over the timeline with recognize that it's there - there just isn't any timeline bar/blip there to denote it, and that's whether it's it's own lane, or contained within a longer span event).
Maybe this is how it's supposed to work? If so, is this something that can be adjusted, so that there's some visual indication of events with no end date/time?
Thank you for your time and effort,David


-----Original Message-----

**Comment by Kordishal** [comment]
Hi, no it is not supposed to be invisible. Have you set a specific fontawesome or rpgawesome icon? Believe some of them do not render correctly and I would be able to confirm if that was the case if I know which ones you used.

Otherwise can you try CTRL+F5 to fully refresh the cache of the chronicle to see if that resolves the issue.

And please tell me your browser / device combination so we can see if that might be an issue.

**Comment by Kordishal** [comment]
I tried a few of the RPGAwesome icons and they all work for me. However, it is important to add the rpg awesome prefix:

- `ra ra-aura` 
- `ra ra-nails` 

Could this be the issue?

This should probably be made clearer as the RPGAwesome page does not add this to the icons each time and the example in the docs is just for FontAwesome.

**Comment by Fornaxus** [comment]
Well.... hell. That would probably be it. 
Also, you're idea of support is to of the line! Thanks again for all of your help. 

Sent from the all new AOL app for Android 
 
  On Mon, Jun 27, 2022 at 12:11, Jonas ***@***.***> wrote:   


I tried a few of the RPGAwesome icons and they all work for me. However, it is important to add the rpg awesome prefix:
   
   - ra ra-aura
   - ra ra-nails

Could this be the issue?

This should probably be made clearer as the RPGAwesome page does not add this to the icons each time and the example in the docs is just for FontAwesome.
