### ISSUE TITLE
Chronicle Setup Wizard does not work properly in Safari browser

### ISSUE THREAD

**Issue by michaeltenner** [worldanvil/worldanvil-bug-tracker#1148]
**World Anvil Username**: MikeTenner

**World / Campaign / RPG Character / Manuscript Title**: N/A

**Feature**: Chronicles

**Related URLS** (To public & visible pages add screenshots otherwise): N/A

**Describe the Issue**
When creating a new chronicle, on the page where user is prompted to select a calendar template the 'NEXT' button is not functional.

**To Reproduce**
1. Go to Chronicles
2. Create a new chronicle3. 
3. Select any calendar template 4. 
4. Attempt clicking on 'Next'

**Expected behavior**
Moving forward in the Chronicle creation process.

**Screenshots**
N/A

**Comment by michaeltenner** [comment]
Issue limited to the **Safari** browser. Works OKAY on Firefox.

**Comment by Xuroth** [comment]
I've deployed a potential fix, but I am unable to test on Safari due to Apple. Can you see if the issues have been resolved?

**Comment by michaeltenner** [comment]
Test on my iPad and iPhone: does not work. I am able to now select *which* calendar type I want but not click on the ‘next’ button.

**Comment by Xuroth** [comment]
Hm, okay. I've updated the information so that is able to work with the last reported features for Safari, but sadly am unable to test (I don't own a Mac to test against, and Safari is only available on Apple's OS'). We typically encourage modern browsers like Firefox and Chrome/Chromium, and you've mentioned it works for those. 

I'll continue checking if there's anything additional I can do to ensure compatibility with Safari's legacy engine!

**Comment by iamromeo** [comment]
Chronicles is a modern tool requiring modern browser architecture to work. Safari has not updated its components to be able to support it. There is no plan for this tool to become backwards compatible especially since all mac users have access to modern browsers (myself included).
