### ISSUE TITLE
Can’t Update World Introduction 

### ISSUE THREAD

**Issue by GalaxyWolf32** [worldanvil/worldanvil-bug-tracker#1150]
World Anvil Username: TheDoctor292 

World / Campaign / RPG Character / Manuscript Title: All (Eceon, Necumia, Ilthci)

Feature: 

Related URLS (To public & visible pages add screenshots otherwise):

![227BB87C-3BA0-4A11-B0C5-8A666909CEF3](https://user-images.githubusercontent.com/89235919/178123592-a2ce51c6-cea6-4e45-a82a-6e51b900772f.png)
![61159789-8AF5-4EE4-A315-542977D23E9D](https://user-images.githubusercontent.com/89235919/178123591-f6b082a8-f81a-4578-8bbb-a7321b2fc308.png)

Describe the Issue
Whenever I try to update the world introduction and save it, the text reverts back to the previous save. I’ve tried different browsers and the issue still remains. 

To Reproduce
1. Scroll down to 'settings’ and start writing in the world introduction and save
2. See error

Expected behavior
I expect the text to save what I have written

**Comment by Kordishal** [comment]
Hi, saving the world settings is not generally borked as it works for me. Is this still happening?

From the screenshots I see nothing wrong, or what could cause the issue. Did you make changes to any other parts of the settings that could be preventing the save from going through?

Otherwise can you copy & paste the new text here so I can check if that is an issue?

Does this issue appear just with this world or with other worlds too? When did this issue first appear?

**Comment by GalaxyWolf32** [comment]
It appears with other worlds too and is still an issue. It first appeared a couple months ago. I also haven’t touched the settings in awhile. 

“/*The tech is mostly holographic with very advanced defect curing technology. Wouldn’t recommend coming here if you don’t like battles because they happens regularly.*/

The native species have been battling since they first set eyes on each other and they can’t find a peaceful way to end it forever. The Irziell’s want peace but the Qieq’ars want revenge for their ancestors. Who will emerge victorious?”

**Comment by Kordishal** [comment]
This text is definitely not the problem. After you save the text and it says it saved in the green box, what do you do after that? Are you going directly to the view the world homepage? And then there you see the old content?

**Comment by GalaxyWolf32** [comment]
I wait a little bit when the save appears which shows the old content. I then go to view the world which is the same.

**Comment by Kordishal** [comment]
Oh right the content on both of the screenshots isn't the same. Do you know how to check the console log for errors when saving? Otherwise can you give me temporary co-owner access to your world? 

My username on World Anvil is [SoulLink](https://www.worldanvil.com/author/SoulLink). If you are not comfortable with that you'll have to screenshot the console output to see if there are any errors.

Press F12 to open the dev console and make sure you are on the Console tab. Then do the steps to add the new content and save. Next switch to the network tab and repeat the process. There check for any lines that are red and have status code of 404 or 500. Make screenshots of those expanded.

**Comment by GalaxyWolf32** [comment]
Just added you

**Comment by Kordishal** [comment]
Ok the saving works fine for me. You have problems on this world too on your end? Have you tried this on a different device?

**Comment by GalaxyWolf32** [comment]
That’s the world i did the screenshots with. I only use world anvil on one device. Maybe it’s a mobile thing
