### ISSUE TITLE
Articles not publishing to world view

### ISSUE THREAD

**Issue by KitFoxglove** [worldanvil/worldanvil-bug-tracker#1163]
**World Anvil Username**: 

KatieKate423

**World / Campaign / RPG Character / Manuscript Title**: 

The City-State of Ormos

**Feature**: 

Articles

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
I cannot seem to view any articles in the "world view" or in the "view" option from the article editing screen.  I can view the article when it is linked in the map, however.

**To Reproduce**
1. Create article
2. Publish article
3. Select "view" option on editing screen 
4. OR Select "World View" from left menu

**Expected behavior**
Body text/article to appear in World View

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

![Screenshot (14)2](https://user-images.githubusercontent.com/109323976/179133222-16e1a9d3-58ac-4f12-a63c-de6faa6cbff4.png)
![Screenshot (13)](https://user-images.githubusercontent.com/109323976/179133228-d362cd26-9661-43d2-8894-9dfe6b7cdf48.png)
![Screenshot (12)](https://user-images.githubusercontent.com/109323976/179133450-bd5ba677-877b-42e8-880b-0ce3e1399222.png)

**Comment by Kordishal** [comment]
What happens when you click the View button? Have you refreshed the page and tried again?

**Comment by iamromeo** [comment]
99% probability that this. is a problem with an unclosed tag.

**Comment by iamromeo** [comment]
Please go through the content of your article and make sure that there are no unclosed BBcode tags.

**Comment by KitFoxglove** [comment]
Hi, thanks for getting in touch.  I have no idea how to do that.  Do you
have a walkthrough?
--Katie

**Comment by KitFoxglove** [comment]
Also, it happens with all of the articles when I try to use the "view"
option while on the editing screen for the article.
--Katie

**Comment by Kordishal** [comment]
Hi Katie!
Is this world private at the moment? Cannot see if on your profile. Since all your articles are affected that is very strange, can you make the world public see we can take a look?

What Dimitris is referring to is that you have a BBCode tag in your content somewhere that breaks the display. This is unlikely the case if it affects all articles unless you have content in a global field. The ones accessible from the world settings.

**Comment by iamromeo** [comment]
If this issue affects all articles this might be an issue with CSS. Specifically font-color  being the same with background or completely opaque. 

We had a similar case some days ago. 

@KitFoxglove  if you can give co-owner access to @Kordishal or myself we can have a look 

@Kordishal  username: **SoulLink**
@iamromeo  username: **Dimitris**

**Comment by KitFoxglove** [comment]
Okie dokie, you both have access.

**Comment by Kordishal** [comment]
I can see the content on all the articles in that world. It is possible that you have a browser extension that affects CSS? Try looking at the articles in a private window / different browser.

Otherwise I am not sure what else we could try.

![image](https://user-images.githubusercontent.com/14262536/179360837-69fa29c1-6920-4d59-8c93-2bdf5ddc1b2c.png)

**Comment by Kordishal** [comment]
![image](https://user-images.githubusercontent.com/14262536/179418339-eec56023-63f7-45fc-abac-6b1165e65ca3.png)
You have set the default base font colour to be invisible.

**Comment by Kordishal** [comment]
And I have changed it to black -> rgb(0,0,0)

**Comment by KitFoxglove** [comment]
I changed the theme to see if it would do anything and it seems like it is
the font color.  The articles will show up with any of the other themes,
but no the "Dungeons & Dragons" one.
