### ISSUE TITLE
Wild Wild Steam theme CSS is broken

### ISSUE THREAD

**Issue by AmeliaNite** [worldanvil/worldanvil-bug-tracker#1181]
**World Anvil Username**: amelianite

**World Title**: Test

**Feature**: Theme CSS is broken

**Related URLS** (To public & visible pages add screenshots otherwise): [Test Character](https://www.worldanvil.com/w/test-amelianite/a/test-person)

**Describe the Issue**
When using a world with the "Wild Wild Steam" theme and editing an article, the vignette, which has its own background, does not show the background on the presentation side, causing the words to blend into the background of the entire article.

This was reported in the CSS-Help channel by Ziggaton. Their world, Dimension X has an article, [Leona](https://www.worldanvil.com/w/dimension-x-coolcomicsc/a/leona-article) that shows the exact same thing in the screenshot provided.

**To Reproduce**
1. Make "Wild Wild Steam" the theme of your world.
2. Create a new article and type in the vignette.
3. Go to presentation mode.
4. See that the vignette's background is not there, causing the words to blend into the background.

**Expected behavior**
The vignette on any article of the Wild Wild Steam theme is broken.

![Screenshot (46)](https://user-images.githubusercontent.com/88216660/180593137-f778248a-9637-420a-8748-df5a327bca5a.png)

**Comment by r2dane2** [comment]
This same issue is affecting other themes as well.  In addition, in blocks set on the content side, the footer is starting inside the content boxes, rather than across the page.

This may be related to these errors seen in the console.

`phidias.js:2 jQuery.Deferred exception: $(...).simpleLightbox is not a function TypeError: $(...).simpleLightbox is not a function
    at HTMLDocument.<anonymous> (https://www.worldanvil.com/js/compiled/display.js?v=016535:124:521)
    at j (https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js:2:29999)
    at k (https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js:2:30313)
    at i (https://script.phidias.docker.worldanvil.com/phidias.js:2:470858) undefined`

`Uncaught TypeError: $(...).simpleLightbox is not a function
    at HTMLDocument.<anonymous> (display.js?v=016535:124:521)
    at j (jquery.min.js:2:29999)
    at k (jquery.min.js:2:30313)
    at i (phidias.js:2:470858)
o1195760.ingest.sentry.io/api/6318881/envelope/?sentry_key=53bc20bac1014079a0d167975587c559&sentry_version=7:1          Failed to load resource: the server`

**Comment by GorkamWorka** [comment]
@r2dane2 those errors are unrelated to the WWS CSS bug.
@AmeliaNite  We are rolling out a new way of handling theme images that will solve that. 
Can you please confirm it solved your issue?

**Comment by AmeliaNite** [comment]
@GorkamWorka Yes, the theme is fixed on both mines and on the world, Dimension X. Thank you.
