### ISSUE TITLE
Maps no longer loading in 'view' mode

### ISSUE THREAD

**Issue by MeisonAsagari** [worldanvil/worldanvil-bug-tracker#1185]
**World Anvil Username**: R.Jones (Meison Asagari)

**World / Campaign / RPG Character / Manuscript Title**: Palehearth

**Feature**: Maps

**Related URLS** (To public & visible pages add screenshots otherwise):
example: https://www.worldanvil.com/w/palehearth-meison-asagari/map/0742d71e-2a52-435c-bde3-2b2af3cfde74

**Describe the Issue**
A clear and concise description of what the issue is.

I have never had an issue before, but logging in today, I cannot view any of my maps.
They still appear in articles where they are linked, and I can 'edit' them from the tree panel on the left, but viewing, either by selecting 'view' in the tree, or clicking directly on them presents the viewer, but does not load the map.

I have tried incognito mode on and off, clearing my browser cashe and using multiple browsers on multiple devices.

**To Reproduce**

1. Go to Left Hand Ribbon of Options
2. Click on Maps
3. Scroll down to any map in the list
4. Click on the 'view' button (eye symbol)

OR

1. Go to any article with a map linked.
2. e.g. this public page: https://www.worldanvil.com/w/palehearth-meison-asagari/a/village-of-arna-settlement
3. Click on the map that is visible there.

**Expected behavior**
The map should load within the tab.

However it presents a black page, as shows in the screenshot attached/URL above.

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!
![map capture](https://user-images.githubusercontent.com/109916971/180658603-5589bda5-8129-428f-bdd0-6b778c4aeff6.JPG)

**Comment by iamromeo** [comment]
Hello there :) It seems like you have an issue with the introduction of your world which affects both the homepage 
https://www.worldanvil.com/w/palehearth-meison-asagari
and the initial loading of maps (since that introduction appears on the sidebar of the map) 

The chances are that you have a piece of BBcode that opens and never closes. Fixing this will fix the issue. 
In order to test it you can cut the world introduction and paste it somewhere else and then save, this should fix both. after that you can go through your text carefully and fix the issue.

**Comment by MeisonAsagari** [comment]
Hello There!

That worked perfectly and immediately!
Thank you so much.

Kind regards,
Ryan.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by iamromeo** [comment]
Happy to help!
