### ISSUE TITLE
Unable to use Categories and Articles in Two Worlds

### ISSUE THREAD

**Issue by PleasantPheasant77** [worldanvil/worldanvil-bug-tracker#1212]
**World Anvil Username**: PleasantPheasant77

**World / Campaign / RPG Character / Manuscript Title**: Fallen Forgotten

**Feature**: Categories

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
An article in one world placed itself under a category of another world. There's also the problem of categories not showing up when I go to put something under them.

**To Reproduce**
1. First I had my main world and decided that some articles I made belonged in another. I created a new world and recreated some of my organization system in this new world, the categories having the same titles as the first world. 
2. After creating the categories I went to remake some articles. 
3. I had my first world, Dime-A-Dozen Dimensions, open in one tab and my second world, Fallen Forgotten, open in another. 
4. The first article creation went fine, no errors. The second article was an organization article that was to go under the 'Governments' category. This category also happens to exist in my first world. 
5. I go to put my article under said category and it doesn't show up. 
6. I try to force it by going to the Articles tab and making a new article under the 'Governments' category. 
7. The article goes in, but they still don't show up with other articles
8. I decide that maybe the articles didn't actually exist and delete them.
9. The article under Governments still says it's under the deleted category
10. I navigate to the deleted category and it brings me to the identically named category in my first world.
11. I switch to the first world and discover that the deleted categories moved themselves to the first world somehow

**Expected behavior**
I make the articles and they stay in the world I made them in.

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!
![image](https://user-images.githubusercontent.com/106975794/182728121-cd105db1-f659-4450-b135-66978418b0ce.png)
![image](https://user-images.githubusercontent.com/106975794/182728472-ae6b268b-031e-4ba2-8b77-3bf0ff564b53.png)

**Comment by iamromeo** [comment]
hello @PleasantPheasant77 but this is a user error - as you described you had been working in two different tabs and you have used those tabs to have two worlds open - something that is not possible/allowed. 
The good news? You can move your articles / categories the same way you actually broke them thought :)

**Comment by Lillydaemon** [comment]
Hi, I just joined and had a very similar issue with my two worlds, but with different steps to get to it. I did have multiple tabs open earlier (I was exploring everything I could do with the site) and a couple did have my two worlds open at the same time so I can understand why they were having issues earlier. However, I logged back in about 20 minutes ago and only had 1 tab open and this is where my experience is different from the previous poster:

1) I logged in and went straight to the articles section in order to continue updating one that I began earlier. I immediately noticed that some of the Categories from my first world had worked their way into the list of in my second world (they did not have the same names) and there were doubles of the basic Categories that are generated upon creation of the world.

2) I set about deleting all of the extra Categories and got it down to what should have been there in the first place (still only 1 tab open)

3) I noticed that the article I had intended on working on was not in the Category folder that I had last placed it in so I clicked on the "Articles" section in order to bring up the "Recently Updated Articles".

4) All of the Categories that I just deleted came back and now all of my sub categories are registering as parent categories.
