### ISSUE TITLE
Map editor does not display map image or markers.

### ISSUE THREAD

**Issue by MalithFlorence** [worldanvil/worldanvil-bug-tracker#1216]
**World Anvil Username**: Malith

**World / Campaign / RPG Character / Manuscript Title**: Azyl

**Feature**: Maps

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
When I want to edit my map it doesn't show up like normal. It's a blank page with an option to edit a marker that I don't even see. I can see it in the presentation mode, just not in the edit mode.

**To Reproduce**
1. Go to Maps
2. Click on 'edit' by Azyl map
3. Wait a few seconds for it to load

**Expected behavior**
I expected to see my map with all the markers and their descriptions, like I did just few minutes ago.

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!
![Zrzut ekranu 2022-08-07 115201](https://user-images.githubusercontent.com/110765882/183285734-2ad7ec34-d637-4f22-b3ff-44e517098e5f.png)

**Comment by Kordishal** [comment]
Hi!

This issue is usually caused either by an image that World Anvil cannot deal with or because of a marker gone wrong. Have you changed the image before this occurred or have you added some markers recently?

For map images the issue can usually be resolved by ensuring the image is a WEBP encoded image.

For marker issues you can either try to edit them or delete the last few you created to see if that resolves the issue. What exactly causes this still is unknown.
