### ISSUE TITLE
Issue with chronical date jumping

### ISSUE THREAD

**Issue by ThunderFirm1337** [worldanvil/worldanvil-bug-tracker#1229]
**World Anvil Username**:ThunderFirm

**World / Campaign / RPG Character / Manuscript Title**: Generic Fantasy

**Feature**: Chronical

**Related URLS** (To public & visible pages add screenshots otherwise): https://www.worldanvil.com/w/generic-fantasy-thunderfirm/chronicle/history-of-the-plane-chronicle

**Describe the Issue**
Whenever i try to do things with dates in the Chronical it always messes up with dates. First, the time displayed with the chronical by default seems nearly random. It doesn't start at the designated start time for the chronical. Then when you use the time jump to jump to a specific date it messes up. For me specifically i have it set in decades and whenever i put in a number under -1000 it just adds 1000 years to it for some reason. For example, i have an event at 16000 BCE, so to jump to it i would need to put in -1600 if i have it set to decades, but when i put in -1600 to jump there it gives me 6000 BCE. I don't know if this issue changes when the numbers get larger but that's just what i was experiencing. 

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by Kordishal** [comment]
Yeah for me the issue only appears with years above 1000.  Go to generally works correctly as long as the year is below 1000. I reported this before but I realise that I did not make an issue here.

**Comment by iamromeo** [comment]
This is not a bug. When you change the Granularity (Years, Decades, Millenia) the JUMP is not in YEARS it is in the unit that you have chosen it to be for example if you are in Decades and you want to go to year 1600 you want the **160th decade** which will mean 160, not 1600 on the JUMP. 


If you read the description you will see that it is changing 
![image](https://user-images.githubusercontent.com/660175/184818075-3a58028e-7f1d-4276-8095-cdf32e3c7d66.png)

**Comment by ThunderFirm1337** [comment]
No this was not resolved, you just ignored what i said. Please read what i actually said. when i put in -1600 decades it went to 6000 BCE. If you go to past -1000 decades it puts a difference of the 1000 decades. so if i put in -1234 decades it would give me the year 2340 BCE. Please actually look into this because i just double checked and it is still a problem

**Comment by ThunderFirm1337** [comment]
Im going to open up another ticket if this goes unanswered because you didn't even look into the issue.

**Comment by Kordishal** [comment]
We did look into the issue. Which is why the Cannot Reproduce label is on it, but forgot to follow up with you. And now I realise that the problem only appears on negative numbers.

@Xuroth The issue is negative numbers starting with -1100 for granularity decade and all those above it. -1099 still works fine. After that something goes wrong with the calculation.

**Comment by Xuroth** [comment]
I've found the location of the issue and am working on trying to fix the formula!

**Comment by Xuroth** [comment]
@Kordishal Can you confirm if the issue no longer appears for you? (hard refresh / ctrl+F5 may be required)

**Comment by Kordishal** [comment]
Everything I tested worked as expected from Decade up to Aeon! Tested with -1600 on all of them and with a range of negative numbers in Decade.

You probably already have that noted somewhere, but the numbers at the bottom need shortcut notations for certain sizes of numbers, because it starts to be unreadable after a while.
![image](https://user-images.githubusercontent.com/14262536/192030350-01e8c76a-c2bb-4462-bc24-dc49d8418041.png)
