### ISSUE TITLE
Can't delete character; button doesn't exist

### ISSUE THREAD

**Issue by TM283** [worldanvil/worldanvil-bug-tracker#1254]
**World Anvil Username**: CaptCharlie82

**World / Campaign / RPG Character / Manuscript Title**: Ptolus

**Feature**: Delete character button

**Related URLS** (To public & visible pages add screenshots otherwise): See screenshot, character name is Karmos
![unknown](https://user-images.githubusercontent.com/112922624/188733691-f1fb0068-8a8f-4fb0-b613-4c479cfdf41a.png)

**Describe the Issue**
There is no way to delete my character from an old campaign. I contacted WA on Facebook and received this explanation: "It looks like the character is still linked to the world or campaign, even if they are deleted, so the delete button isn't appearing."

**To Reproduce**
1. Go to my homepage
2. Click on KARMOS with the eye symbol on the left sidebar, click EDIT button
3. Scroll down to DELETE CHARACTER dropdown box on right
4. See error: The dropdown is completely blank, no text or options

**Expected behavior**
A delete button that would entirely remove the sheet for this character

**Screenshots**
I added a screenshot of the blank DELETE CHARACTER dropdown.

**Comment by iamromeo** [comment]
Character articles cannot be deleted if the article is connected to a HERO profile. 
Delete the hero to delete the article

**Comment by Kordishal** [comment]
@iamromeo The character to be deleted is a RPG / HERO Character. Not the article.

The problem here is that the World this character was connected to was delete by the Storyteller. Now this user can no longer delete the character because it is connected to a ghost world. 

The Character Access Rights section does not allow them to leave the world. And because they are still considered part of a world the RPG Character cannot be deleted.

**Comment by iamromeo** [comment]
We need to allow deletion of a character IF 
- the world they are attached to is state: archived
- the world of the campaign they are attached to is state: archived

**Comment by iamromeo** [comment]
Related to:  #1236

**Comment by Kordishal** [comment]
You should now be able to delete that character!
