### ISSUE TITLE
Writers & Advanced Writers are able to view all articles on a world + see their contents

### ISSUE THREAD

**Issue by Hanhula** [worldanvil/worldanvil-bug-tracker#1269]
**World Anvil Username**:
Hanhula
luulunacy

**World / Campaign / RPG Character / Manuscript Title**:
Istralar
Of Starfell and Nightfall

**Feature**: 
Athena / article list

**Related URLS** (To public & visible pages add screenshots otherwise):
https://www.worldanvil.com/world/athena/

**Describe the Issue**
A clear and concise description of what the issue is.

Writers and advanced writers are able to see every article on a given world, including its categories, and can access the vignette and other hidden information. As writers are often players, this is a major issue and could potentially spoil huge points in campaigns.

**To Reproduce**
1. Set another person as a Writer or Advanced Writer
2. As the Writer, click on Articles / otherwise access the Article List
3. See error
4. Attempt to expand details of articles: this also works

**Expected behavior**

I expect writers and advanced writers to only have access to what they are specifically allowed to see. They should not be able to see the article list or access the secrets written into each article. Having access to everything means that a player given Writer permissions to, say, write their love interest's article could then find the category for Antagonists and spoil the campaign for themselves.

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

![unknown](https://user-images.githubusercontent.com/22137517/190933279-1cc943fe-a9ee-40e2-8667-63b995d18502.png)

![SPOILER_unknown](https://user-images.githubusercontent.com/22137517/190933284-01a06e8c-d309-4ea4-8b3b-644ae891742f.png)

Both of the above screenshots are from the perspective of writers, not authors.

**Comment by Hanhula** [comment]
Issue was raised in #help in Discord by @lulunacy and I subsequently confirmed with my own players.

**Comment by iamromeo** [comment]
This is not a bug - this is how the system works. Editors/Writers have access to everything

**Comment by Kordishal** [comment]
@Hanhula That is not how writers see the world. Writers can only see articles they created. Nothing else. Same for advanced writers.

![image](https://user-images.githubusercontent.com/14262536/190956211-af8e4979-fdb1-4ace-8ac3-93732df8504c.png)


If they do see some on their end then that would be a bug, but it works on my side.

**Comment by Hanhula** [comment]
@Kordishal They do absolutely see some as they can access the article list from the view pages of the world; the screenshots I shared were of both my player's view and of @lulunacy 's player.

@iamromeo 
> Writer can create articles as drafts, but they can't publish them nor edit existing articles. They can't view private content unless they are also a subscriber.

The codex lists this on [this article ](https://www.worldanvil.com/w/WorldAnvilCodex/a/coauthors). If the intent is for writers to be able to see everything on a world, including content marked as private or draft, that should probably be updated - as far as I'd known, it was intended for them to only be able to edit and affect articles they were set as the author of. 

I'll write up a feature suggestion for a writer rank that can only see articles they have access to, since I want my players to be able to write the articles for their homes and families. Thanks!

**Comment by Kordishal** [comment]
@Hanhula Writers being able to see the full ToC is a known issue. Though I can't seem to find the issue related to that right now.

However, if they do see the normal view as writers / advanced writers then that would indeed be a problem. On my test account I only see the limited interface and cannot see private / draft articles. Do any of your players have accounts with subscriptions? And do some of them have free accounts? Otherwise I don't see how it could be different.

**Comment by Hanhula** [comment]
@Kordishal Yeah I did a search for a related issue and couldn't see one, so posted mine.

TheDumbOwl does indeed have a Journeyman level subscription. I removed him from my advanced writers list immediately after posting the bug report because I can't risk them spoiling my campaign for themselves, but if you need me to test, I can try doing something later on today.

**Comment by Kordishal** [comment]
@iamromeo Hanhula was able to figure out the issue:

- Writers can now access the Athena interface when they go directly to the link. They can find it because there is the link on the articles in the editor nav bar for them.
- This definitely was not the case in the past.

- They appear to be able to access all the world menu pages that they were not able to before.

**Comment by iamromeo** [comment]
@Kordishal Writers can be used by players if the storytellers trust the player that helps them
Yes they do have access because they are editors, just with not so expansive rights. 

The Apollo / Athena access if probably something we should address but it is not on their interface -- again is someone is a Writer they are already trusted with editing rights so it is a soft issue but we will address it.

**Comment by lulunacy** [comment]
I'm sorry to comment on this, but I do think, as a client, this should be made clearer on the features list because I would never have signed up for WA if I had known that writers would have access to everything since my players write their own backstories and secrets and to have that available to each other despite privacy roles, negates the need for me to use WA. For other, future customers, I would suggest making this "feature" completely transparent. Thank you.

**Comment by Hanhula** [comment]
@iamromeo Just to note, the access to Athena is on their interface due to the top bar on an article's view mode having the link out to Athena, even for writers!

@lulunacy To clarify a little, it seems like Writers does work like how you and I see things, so long as nobody clicks or finds the links out to Athena (the big article list) or Apollo (the image manager), and Dimi just said they'll address that in the future. What my strategy is now is that I've removed all writers from my world to keep them from accidentally finding things they shouldn't.

It's probably important to note that in the meantime, you should try using Heroes. Players can edit their own Heroes characters and have it reflect in the article the character is linked to, and they can write journals and secrets in that interface as well.
