### ISSUE TITLE
Unable to Delete World

### ISSUE THREAD

**Issue by Wiickles** [worldanvil/worldanvil-bug-tracker#1273]
**World Anvil Username**: Wiickles

**World / Campaign / RPG Character / Manuscript Title**: The Sword Coast / Troupe de Stooges

**Feature**: "Delete World"

**Related URLS** (To public & visible pages add screenshots otherwise): Settings > Delete World leads to this 404 page: https://www.worldanvil.com/world/daedd608-0120-4993-ba5d-2ee8a3ecd398/delete

**Describe the Issue**
When attempting to delete my world and campaign (The Sword Coast & Troupe de Stooges, respectively), I was instead redirected to a 404 page.  When I navigated back to the World Anvil home page, the world and its related information are all still available and have not been deleted.

**To Reproduce**
1. Go to world.
2. Click on settings.
3. Scroll down to Delete This World.
4. Open drop-down panel.
5. Click on 'Delete This World'.
6. Confirm deletion.
7. Arrive at 404 page.  World is not deleted.

**Expected behavior**
I assumed it would delete the world and related campaigns and pages, as the warning states.

**Comment by iamromeo** [comment]
Hello there @Wiickles 

Please make sure that you follow the instructions on the screen when you try to delete a world to the letter. Specifically: 

In order to delete your world make sure that you have already done the following.

- Delete any campaigns associated with the world
- Delete any manuscripts associated with the world
- Expel any RPG Characters from the world
- Remove any subscribers and co-authors from the world
- Delete subscriber groups from the world
