### ISSUE TITLE
Article links in marker popups are linked to map editing in map editor interface

### ISSUE THREAD

**Issue by lyervo** [worldanvil/worldanvil-bug-tracker#1275]
Browser - Chrome

How to replicate -

Create map
Create a marker
Select the option to quickly create an article and link it in the marker with a character article
Finalize and create the marker
Hovering on the marker and clicking on the article link while in map edit mode will not bring you to the article but redirect you back to the map edit page

**Comment by Kordishal** [comment]
As far as I can tell this has nothing to do with how the article is created, but just that all article links in the map marker popups redirect to the map editor instead of the specific article edit or view page. While in the map editor interface.

![image](https://user-images.githubusercontent.com/14262536/191281450-201af190-c369-4947-ace5-b8198b47ee47.png)

**Comment by iamromeo** [comment]
That is done on purpose on the editing page since the link is the just to display the link not to navigate to the page.
