### ISSUE TITLE
Worlds with custom URL load slowly

### ISSUE THREAD

**Issue by Deleyna** [worldanvil/worldanvil-bug-tracker#1282]
Just noting this for future thought. It isn't critical, but it could become an issue as more worlds are built.

**Please make sure to fill out the template to the best of your ability. Add your information to the right of the colon as requested by the label! More information helps us track down the issue and fix it. Bug reports that do not let us reproduce the issue cannot be addressed. Thank you for your time in helping make World Anvil better!**

**World Anvil Username**: Deleyna

**World / Campaign / RPG Character / Manuscript Title**: Aubadeon

**Feature**: Being able to point a custom domain name to the website built with World Anvil

**Operating System**: Windows 10

**Browser**: Firefox, Edge (much better in Edge...), 

**Device / Device Model**: desktop computer, cabled internet, so generally very fast

**Related URLS** (To public & visible pages, add screenshots otherwise): Aubadeon.com

**Describe the Issue**
I'd noticed other users mentioning that their custom URL sites loaded much slower than they do on World Anvil directly. Now that I've got one of mine working, I'm seeing the same. I'm hoping that by pulling all of the info together, maybe one of your brilliant folks will see something that can be done easily. If not, I think we're all okay living with it, but it will effect our SEO dramatically.

Here is a video showing the speed of loading on a fast internet connection:
https://capture.dropbox.com/VFqfICCeMmwf8lCN

I'm also attaching a Google PageSpeed Insights report

**To Reproduce**
1. Go to aubadeon.com
2. Wait and watch the page load

You can compare the speed with this page:
https://www.worldanvil.com/w/aubadeon-deleyna

**Expected behavior**
Page Speed is a ranking factor for search engines. My hope is that it would load at (or close to) the same speed as it does when accessing the world without using the custom URL.

**Screenshots**
[PageSpeed Insights Aubadeon World Anvil.pdf](https://github.com/worldanvil/worldanvil-bug-tracker/files/9630328/PageSpeed.Insights.Aubadeon.World.Anvil.pdf)

I've attached a complete page speed report. The size of the images - that's on me. I haven't tried uploading WebP images yet to know if that works.

If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by iamromeo** [comment]
**Initial Thoughts**
WorldAnvil.com is using CloudFlare to upload images on a Super Fast CDN, which means that even massive not-optimised images are being optimized and loaded quickly and easily. 

Private domains of worlds that do not optimise their images native (when uploaded) do not get this benefit because it is locked on the domain. 

In order to optimise the loading speed you can: 
1. Optimise the images uploaded 
2. Subscribe to a professional CloudFlare (or other domain Image optimization CDN system) for your domain. 

**Course of Action**
We will investigate if the bridge is responsible for this in any way and get back to you on it.
