### ISSUE TITLE
Images cannot be added to articles

### ISSUE THREAD

**Issue by Rawilow** [worldanvil/worldanvil-bug-tracker#1347]
I do not know why, but I can't seem to add images in my articles. When I do, I just get the "image" placeholder logo.

Rawilow:

Faucongris - Version Rawilow:

**Browser**: Chrome 

**Device / Device Model**: HP

![Capture d’écran 2022-11-07 191000](https://user-images.githubusercontent.com/117694116/200442292-7a4abcd5-5072-4924-90d7-56880c1cd49c.jpg)

**Comment by Lyraine-Alei** [comment]
instead of using the Insert Image button, if you already have the image on
your clipboard from uploading to World Anvil, just right click and hit
paste.

If you go into Source Mode with the button reading >_ you would find
[img:[img:numbers here]] and the [img: and the ] are what are causing the
issue.
