### ISSUE TITLE
Creating a new character and/or adding them to a campaign wiped a large amount of info from another character profile

### ISSUE THREAD

**Issue by meffewToo** [worldanvil/worldanvil-bug-tracker#140]
**World Anvil Username**: meffew_meff

**Feature**: Characters

**Describe the Issue**
I had created 1 character with a filled out profile and added them to another user's campaign through an invite link. Then I created another character, and filled out the profile. When I added the new character to the same campaign, I attempted to return to the first character's profile to review it, but all of the information on the "extended profile" tab had been erased, except for the "short bio" section. I don't know at what point in the process this happened, but I did not interact with any of the text sections on the original character profile, except the "short bio" section.

**To Reproduce**
I attempted to reproduce the problem by doing the following:
1. +New Character
2. Fill out profile sections with dummy text
3. Add to campaign through invite link
4. Return to previously created character profile
This did not reproduce the issue, however.

**Comment by iamromeo** [comment]
Hello @meffewToo 

This is not the result of joining a campaign but a result of having two characters open on two different browser windows at the same time while, as expected, only one of them is currently active. Your updates overrode the character which only appeared active because you opened it before opening the one that was in fact currently active. 

Make sure that only one character/world is always active and do not use multiple windows.
