### ISSUE TITLE
Interactive table - Long text column requires double click to "update"

### ISSUE THREAD

**Issue by MGatta** [worldanvil/worldanvil-bug-tracker#158]
**World Anvil Username**: MGatta

**Feature**: Interactive table

**Describe the Issue**
For each row of an interactive table with a long text column, WA prompts the user to click twice on the button "update" to save the contents of a row into the actual table.

**To Reproduce**
1. Go to create an interactive table
2. Add a long text column
3. Add a row
4. Add text in the long text column
5. Click update
6. Click update again

**Expected behavior**
I expect to only have to click update once.

**Screenshots**
Finished text writing: 
![image](https://user-images.githubusercontent.com/80196715/114679654-a9456d80-9d0c-11eb-8d29-5434de5fe082.png)
After one update click, you have to click once more:
![image](https://user-images.githubusercontent.com/80196715/114679721-b82c2000-9d0c-11eb-883e-6768414b2624.png)

**Comment by Xuroth** [comment]
Thanks! This was caused by a CSS/styling issue overriding the Table's built-in style. When the field was no longer focused, the font size would increase, causing the button to shift downward a bit - and causing the script to miss the click event. A deployment including the fix for this is pending and will be applied after review and approval.
