### ISSUE TITLE
Cant access map tooltips on mobile

### ISSUE THREAD

**Issue by Soulwing98** [worldanvil/worldanvil-bug-tracker#191]
**Soulwing**:

**Accessible map tooltips**: 

**Describe the issue**
I created a map and linked it into an article. Some of the marker‘s pop-ups have tooltips embedded in them. While I can read normal ones on mobile, I can’t open those in the popup at all.
They just get marked, nothing more.
![A8704582-79CD-414C-BE2F-5871B5DC6916](https://user-images.githubusercontent.com/83096168/115931323-3b770f80-a48b-11eb-82e4-cd0aa95ae64c.jpeg)

**Comment by iamromeo** [comment]
Hello there @Soulwing98 this is not an issue with mobile only, this is a generic issue and sadly I do not think that will ever be possible to render. 

This is due to the double bubbling that happens. 
We can document this, but due to it's trivial severity and quite hard to achieve implementation I think it will not be actioned
