### ISSUE TITLE
Marker creation on map not working

### ISSUE THREAD

**Issue by marsroma** [worldanvil/worldanvil-bug-tracker#205]
Hello I'm Mars Roma, 

I am working on my world building of Teraan and when I was using the map Interface to add markers I experienced a glitch, at first I did it in the view mode to add a bunch of markers quickly and when I refreshed it would not show any markers. I have done a few maps with these markers but now any map I try to work on is experiencing these problems I've tried to delete the map and start over thinking that might help but it did not I also tried to edit in the edit menu one at a time and it did not load. Once place a marker and try to go to the edit map page the map does not show up any more.

**Comment by Kordishal** [comment]
Hi!

Issues with the map and marker creations are often caused by an outdated cache or extensions which interfere.

In order to check if this is the case simply open the map in a private/incognito window in your browser of choice, log in and then attempt to create a marker. 

If this works then return to the normal window and hard refresh the cache. For Firefox & Chrome, this can be achieved by pressing CTRL + F5. 

If this does not resolve the issue start disabling/uninstalling extensions of the browser one at a time.

**Comment by marsroma** [comment]
That fixed my issue thank you very much!

**Comment by marsroma** [comment]
So that did help the issue at first but now it popped up again and clearing the cache does don't fix it and I do not have an extensions.

**Comment by marsroma** [comment]
I have tried it on a couple different devices to make sure it is not my device having the issue

**Comment by Kordishal** [comment]
You will have to be more specific about what does not work. The easiest way would be if you came to the Discord server and ask in the help channels. Then we can see what the issue is.

**Comment by Kordishal** [comment]
The markers were created but did not display. Anyone else who encounters this issue should make sure to check the marker list to see if they exist.

When a marker is broken it fails to display any of them.
