### ISSUE TITLE
Error 500 when trying to load Campaign Plots

### ISSUE THREAD

**Issue by Exmanx24** [worldanvil/worldanvil-bug-tracker#30]
**xxmanx24**:

**Campaign Icewind Dale: Rime of the Frostmaiden**:

**Plots**: 

**https://www.worldanvil.com/heroes/campaign/plot/list** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
Error 500 when trying to view plots for this campaign

**To Reproduce**
1. Go to 'campaigns'
2. Click on 'plots'
3. See error

**Expected behavior**
Should show plots

**Screenshots**
N/A

**Comment by iamromeo** [comment]
This issue is outlined on the codex and on the video for campaign management. 

The reason it occurs is that you have set a plot to be at the same time the parent and child of some of its ancestors (or directly) 

Solution: 
1. Go to Articles & Categories
2. Go through your plots and fix the infinite loop that was created
