### ISSUE TITLE
Articles & Categories not saving category changes

### ISSUE THREAD

**Issue by TrollyTheSolly** [worldanvil/worldanvil-bug-tracker#31]
**World Anvil Username**:
Tornak
**World / Campaign / RPG Character / Manuscript Title**:
World - The Northern Realms
**Feature**: 
Articles & Categories
**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
A clear and concise description of what the issue is.
When I move an article to a category, the change shows that it has worked however when I go into that category the article is not there, and it returns to uncategorised when I refresh the page

**To Reproduce**
1.  Go to Articles & Categories
2.  Move an article to a different category
3.  Check the new category, the article will not be there and will be back in uncategorised

**Expected behavior**

Moving the article to the new category should move it there and the change should be saved.
**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!
https://gyazo.com/238a3f35561312cec7c47aea3605abae

**Comment by TrollyTheSolly** [comment]
I tested this issue with Chrome and it worked, seems to only be a problem on Firefox for me

**Comment by iamromeo** [comment]
This cannot be reproduced on Chrome or Firefox on my end. Potentially this is an issue with the loaded extensions/plugins on the browser or the version of the browser

**Comment by Kordishal** [comment]
I cannot reproduce the issue either but I know that issues with the drag & drop functionality come up in the help channels fairly regularly. Usually, people complain about how their categories are jumbled up randomly. 

In all cases, it's that the drag & drop visualizes one thing but actually saves something else. I always direct them to use the weight and category assignment to the right because it's impossible to make this issue appear consistently. 

This is also the reason why I never reported it. I sometimes get an issue where the highlights of the category, where you drag an article, does not disappear after moving away. 

So yeah there is an issue sometimes, but it has been impossible to pin down and might, as you say, be caused by interactions with other systems as only a small subset of users experiences this. But at the same time, it is common enough that we have someone on Discord once every other week.

**Comment by iamromeo** [comment]
The regularly reported issue is not relevant to this one. I know what the issue is with that - hard to fix but in my remit

**Comment by Kordishal** [comment]
Ah sorry, yeah then I don't know how to reproduce this issue either.
