### ISSUE TITLE
Freezing issue

### ISSUE THREAD

**Issue by meruem2** [worldanvil/worldanvil-bug-tracker#310]
**World Anvil Username**: Meruem2

**World / Campaign / RPG Character / Manuscript Title**: Kingdom of Divitiae

**Feature**: 'Person' article in D&D 5e Campaign

**Related URLS** (To public & visible pages add screenshots otherwise):https://www.worldanvil.com/world/b20e1169-0dc7-4367-b780-cfc40f6714e1/summary

**Describe the Issue**
When entering an article in the 'person' section, the Browser (Firefox) freezes. In the other sections I tried this did not happen and restarting my pc did not help.

**To Reproduce**
1. Go to 'Dashboard or Articles&Categories'
2. Click on 'create character or on edit on an article in the person section'
3. Freeze

**Expected behavior**
It should not freeze the browser.

**Comment by Kordishal** [comment]
Hi, this is not a general issue that can be reproduced. A freeze within the browser usually happens if it loads too much data at once.

1. Please attempt to refresh the browser cache with CTRL-F5 or from the settings.
2. Attempt to do the same actions in an incognito window. If this works then an extension of yours is prevent the website from functioning properly.

If neither of these solutions resolves the issue please provide additional information such as screenshots where the issue occurs exactly. Specific articles etc. I will close this issue in the meantime but you can simply continue to reply here.
