### ISSUE TITLE
Formatting in World Anvil

### ISSUE THREAD

**Issue by Winter-Tempest** [worldanvil/worldanvil-bug-tracker#324]
**World Anvil Username**: Lesesnee

**World / Campaign / RPG Character / Manuscript Title**: Halruaal

**Feature**:  Formating

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
**The formatting in the edit tool will not save or carry over into the end product.  For instance I set my paragraphs to have a gap in between them and the end product mashes all my paragraphs into one long text block.**

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by Kordishal** [comment]
This is an issue caused by the Plato editor. It is likely that there is some confusion as to where the formatting BBCode is actually located.

Check in source mode that the [p] tags are all properly set and closed.

The [Guide on Text Editors](https://www.worldanvil.com/w/WorldAnvilCodex/a/text-editors) explains how you get there.
