### ISSUE TITLE
Plato Editor prevents Backspace from registering in Undo-Queue

### ISSUE THREAD

**Issue by Kordishal** [worldanvil/worldanvil-bug-tracker#33]
**World Anvil Username**: SoulLink
**Feature**: Plato Editor

**Describe the Issue**
When using backspace in the Plato Editor to delete more than one character the CTRL-Z does not undo this action.

**To Reproduce**
1. Write something in Plato Editor
2. Select all the text (with CTRL-A, double click, or SHIFT-ARROW KEy)
3. Press Backspace to delete the selected text.
4. Press CTRL-Z to undo

**Expected behavior**
CTRL-Z should bring back the deleted text.

**Comment by Xuroth** [comment]
This is a problem with the core library that Plato is built on, and how it interacts with the user's browser's default behavior. Unfortunately, with the current structure, this is not possible to fix without rewriting the core itself, and therefore must wait for the redesign of Plato (where I'll be replacing the core with a stateful editor base).

If this bug is manipulating article content and breaking things, it is advised to switch Editors in the user's Interface Settings page to Euclid. While it is not as user-friendly due to use of raw bbcode, it does not have the parsing/event issues present in Plato.
