### ISSUE TITLE
UTD abbreviation changed

### ISSUE THREAD

**Issue by Matoikey** [worldanvil/worldanvil-bug-tracker#405]
World Anvil Username: Matoikey

World: Garnia

Feature: Timelines

Issue Description: Within any created timeline, UTD has been replaced with era abbreviations created within a calendar before the calendar migration. (ADG and BDG for reference.) As a note: I have tried creating two new timelines, one with the old calendar that originally had the ADG and BDG era abbreviations (Allsunder Calendar for reference.), and one with a newly created blank test calendar. In both cases UTD still displays as the same incorrect abbreviations.

1. Go to, https://www.worldanvil.com/dashboard/
2. Click on, Timelines on the lefthand side-bar.
3. In the window on the right, fill out the "TITLE" field.
4. Click on, "Create Timeline".
5. Under the new timeline, click the add an era dropdown on the righthand side.
6. Fill out the, "TITLE" an "START DATE (UTD)" fields.
7. Click on, "Create Era".
8. Era will now display the incorrect abbreviations: ### ADG > 0 BDG
Side-Note. Most places the abbreviation UTD should display it has been replaced with ADG, this is just one example to have the error display.

Expected behavior: The abbreviation that is supposed to appear, instead of ADG or BDG, is UTD.

Screenshots:
![Timeline 2](https://user-images.githubusercontent.com/86850343/124316132-ae69ca00-db4f-11eb-9c44-f8e627bbfcf2.png)
![Timeline 3](https://user-images.githubusercontent.com/86850343/124316144-b1fd5100-db4f-11eb-82f7-dbeaf91ec5cb.png)

**Comment by Lyraine-Alei** [comment]
I believe that these are the abbreviations you set in your World Configurations, as timelines use those abbreviations for their timeline instead of using UTD for dates (so instead of UTD for a Real-Life timeline under the Gregorian Calendar, it would be using BCE and CE instead of UTD).

But this sounds like the feature is working as intended, at least to me, is it's intended to use your world's configuration abbreviations. Unless this is something being vastly misread by me and you don't have abbreviations set up or something else entirely?

**Comment by Matoikey** [comment]
Thank you very much, this is the exact solution to my problem.
I had been speaking with someone over their Twitter account and they had told me to open a ticket here, but this is either where I changed this, or the calendar had this option previously and it had passed that information into this field.

Thanks again!
