### ISSUE TITLE
"Open in new tab" option is ignored when using INSERT LINK in Plato Editor

### ISSUE THREAD

**Issue by dprothero** [worldanvil/worldanvil-bug-tracker#44]
**World Anvil Username**: dpro

**World / Campaign / RPG Character / Manuscript Title**: Barovia

**Feature**: Maps -> Markers -> rich text editor -> insert a link -> Open in new tab

**Related URLS** (To public & visible pages add screenshots otherwise):
![image](https://user-images.githubusercontent.com/1897006/110258181-19b2df00-7f56-11eb-9c90-95129aaf5cef.png)

**Describe the Issue**
When you insert an external link and select the "Open in new tab" checkbox for the DESCRIPTION field of a map marker, the rendered link in the marker popup opens the link in the same tab, not a new one.

**To Reproduce**
1. Edit or create a Map
2. Add a new marker
3. In the DESCRIPTION for the marker, insert an external link and check the "Open in new tab" box.
4. Save the marker.
5. Click "Open in Presentation Mode" for the map
6. Hover over the marker to get the popup
7. Click the link... it opens the external link in the SAME tab, not a new one.

**Expected behavior**
When clicking the link, it should open in a new browser tab.

**Screenshots**
![image](https://user-images.githubusercontent.com/1897006/110258261-9219a000-7f56-11eb-9f0f-bc6c0ede1c9d.png)

**Comment by Kordishal** [comment]
Hi, this issue is not related to the location you put it in, but to that checkmark not actually working. In order to fix it simply edit the created code to include the tab option:

`[url:https://dndbeyond.com|tab]My Link Text[/url]`

**Comment by Xuroth** [comment]
As Kordishal advised, a workaround would be to adjust the bbcode to use `|tab` in the url bbcode parameters. The checkmark not working is a recurring issue that appears periodically in Plato when it is updated due to a parsing issue in the core library (where it sometimes removes certain parameters from bbcode tags that have multiple optional values). This will be updated in the next version of Plato, when I get a chance to rebuild it.
