### ISSUE TITLE
Session time out while editing falsely indicates that content was saved

### ISSUE THREAD

**Issue by Rapunzel77** [worldanvil/worldanvil-bug-tracker#463]
**World Anvil Username**: Rapunzel_77

**World / Campaign / RPG Character / Manuscript Title**: Herrin der Nachtblauen Tiefen

**Feature**: Safe / Auto Safe

**Related URLS** (To public & visible pages add screenshots otherwise): Any page anywhere

**Describe the Issue**
Over the last sessions I noticed that only part of the "Report Title" of the RPG session was saved successfully. After some time it was not stored any more. First I did not know why, but today I got the "saved successful" message and then switched to a different page (which I normally do not do). There I got an error message indicating that I was not logged in (any more). And yes after logging in the RPG report was only partially captured and stopped in the middle of the session.

**To Reproduce**
1. Create new RPG session Report (or likely any other article)
2. Click on 'edit"
3. Edit for a couple of hours >4
4. Safe periodically
5. Notice that the content is successfully changed (at least is indicates so)
6. close and come back the next day
7. open article and see that some things are missing as the login session timed out while editing

**Expected behavior**
At least there should be an indication on manual safe that it did not work because the session terminated. Better would be to allow to re-login or refresh the session to continue edition without data loss. Even better would be to keep the session alive while editing. 

**Screenshots**
none - missing things are not clear as only I know that I typed them :)

**Comment by Kordishal** [comment]
Today there was a session timeout for all users a warned by the notice. It is possible that this issue is related to that reset. If that is the case then this issue should no longer appear in the future. 

I cann't reproduce the issue with the steps provided. Which is why I will close this issue. Please reply to this issue should you experience this issue again in the future.

There are plans to improve session timeouts in the future to protect users from overwriting content (for example when editing on multiple devices) which probably will also help with this issue.
