### ISSUE TITLE
Dozens of line breaks being inserted into generic statblocks.

### ISSUE THREAD

**Issue by TrueBlueCorvid** [worldanvil/worldanvil-bug-tracker#478]
**World Anvil Username**: TrueBlueCorvid

**World / Campaign / RPG Character / Manuscript Title**: The Shattered Lands?

**Feature**: statblock

**Related URLS** (To public & visible pages add screenshots otherwise): https://www.worldanvil.com/sheet/794265/view

**Describe the Issue**
The viewable page has a large amount (sometimes dozens!) of line breaks (<br>) inserted between normal text and tables.

**To Reproduce**
1. Create a statblock with the "Generic Text" type.
2. Type a line of text and insert a table below it.
3. Save and view. (I checked on both Firefox and Chrome.)

**Expected behavior**
There should be no line breaks, or there should be only the amount of line breaks I put in the editor.

**Screenshots**
How it looks in the editor:
![image](https://user-images.githubusercontent.com/88314705/127835112-6ee1085f-74e8-47dc-b316-d43cc8a75e0d.png)

How it looks in view mode:
![image](https://user-images.githubusercontent.com/88314705/127834867-cd16f55e-6341-4ddd-9b8f-6acc485860e6.png)

**Comment by Kordishal** [comment]
Can you try switching to the Euclid editor and clean up the BBCode to see if the issue persists? Or at least go into source mode. Most likely the table BBCode is a bunch of codes on lines by themselves. In the statblock system, this leads to the creation of empty lines which then are turned into line spacers.

Editor switching: [Link](https://www.worldanvil.com/w/WorldAnvilCodex/a/text-editors)

**Comment by iamromeo** [comment]
This is not a bug - please refer to the documentation. When creating tables the way you do above you should be mergin the lines together.

**Comment by TrueBlueCorvid** [comment]
I tried what Kordishal said and removed every single line break in the table source and that did indeed fix the problem briefly. I saved and viewed the file and the table and text looked as they should. However, when I tried to edit the file again and looked at the source, all the table cels had gone back onto their own lines, so to fix it I would have to erase every single line break every time I edit the file. This isn't a permanent fix, it's a temporary workaround.

I used the visual editor to insert tables -- I didn't go into the source and create the tables incorrectly. Also I'm not sure what documentation you want me to refer to -- I read and watched what tutorials I could find on this feature both before starting and while trying to troubleshoot this problem and didn't see anything about this. I can't see where I did anything unexpected that should have caused the editor to behave strangely.

With all due respect: if this behavior is not intended, then doesn't that make it a bug?

**Comment by Kordishal** [comment]
There is a bit of a misunderstanding. It is not a bug, because everything is working as intended. 

There is an user experience issue because the Plato / Visual editor and the Statblocks are interacting in a bad way. Plato basically enforces a certain structure of code (which I did not know).

That being said to get around this you can either change the settings to always be in source mode first or switch to the Euclid editor. This is the recommended editor at this time, because Plato has a number of issues.

These issues will be addressed in a future update to that editor, but until then it won't be changed. Which is why this issue was closed.

@iamromeo And I don't really know what documentation you are referring to either. I don't think this specific issue is documented anywhere?
