### ISSUE TITLE
Save don't work

### ISSUE THREAD

**Issue by Rixadzin** [worldanvil/worldanvil-bug-tracker#499]
**World Anvil Username**:Rixadzin

**World / Campaign / RPG Character / Manuscript Title**:Placeholder

**Feature**: Save changes

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
A clear and concise description of what the issue is.
I was writing an historical event. After I finished I clicked on save changes and went to look at how it would look. However only half of what I had written (first half) was there. This happened yesterday as well when I was writing about a character.

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by Kordishal** [comment]
Hi. We won't be able to help with this little information. My guess would be either you have some invalid character in your content that prevents saving (like emojis) or have the same editor open in different tabs and have overwritten some progress with an older version.

Best to go to the [Discord](https://worldanvil.com/discord) server for these kinds of issues.

**Comment by Rixadzin** [comment]
https://github.com/worldanvil/worldanvil-bug-tracker/issues/499#issuecomment-898647979
Then please tell me what I need to do... I can't screen shot every single second of my writing. How am I gonna prove that something was now saved? It is gone so I can't show it.

**Comment by Kordishal** [comment]
I didn't say that I don't believe you. It can happen as I've stated. There just isn't anything we can do to help you with the information you've provided. Which is why I closed the issue. 

Make sure to not have different tabs with the same editors open and make sure that everything is saved before closing the tab (e.g. refresh the view in a different tab). 

World Anvil also cannot restore the lost content for a single historical event.

**Comment by Rixadzin** [comment]
But this is what my bug report was about. That sometimes the save function did not work. I was never told when it did not work or when it did. From the video tutorial on the site I was told to save about every 5 minutes. However what I wrote was still not saved.

**Comment by Kordishal** [comment]
Yes. However, without knowing the exact circumstances, it is impossible to reproduce and fix. It is true that World Anvil is not very chatty about not saving correctly, but it only happens in very rare and specific circumstances.

**Comment by Rixadzin** [comment]
But I can't recreate the circumstances either as sometimes is saves, sometimes it doesn't. My whole bug report was that several times I have had it that when I click the "Save changes" button, it still says saved (next to the bell icon on the top right) but when I then go back to watch it, it did not save. When this then happened a few times (about 1 in every 3) I wanna report it.

**Comment by Kordishal** [comment]
Sorry, I did not understand from your report that the issue was with articles and continues to happen. There is a known issue that pressing the save button does not save new content when that content has been added exclusively with the mouse. This can be adding formatting via the toolbar buttons, adding spellcheck suggestions or copy & paste via context menu.

To avoid this issue just make sure that you press *any* keyboard key to trigger the auto-save. Then pressing the save button is not necessary.

And just to be clear, the issue does not repeatedly appear when saving Historical Events, right? Because those are two completely different save systems and have no connection. Then it would be a different issue. I am asking because your original report stated that you were writing an Historical Event, which is not the same thing as an article.
