### ISSUE TITLE
404 when attempting to edit a campaign PCs Character Sheet

### ISSUE THREAD

**Issue by kc0mlp** [worldanvil/worldanvil-bug-tracker#526]
**World Anvil Username**: kc0mlp

**World / Campaign / RPG Character / Manuscript Title**: Eberron: Echo of War a D&D 5e Campaign [https://www.worldanvil.com/w/eberron-campaign-setting-kc0mlp](https://www.worldanvil.com/w/eberron-campaign-setting-kc0mlp)

**Feature**: Editing Character Sheets of Players

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
Upon clicking the "Edit Sheet" button for an existing PC a 404 page is shown.

**To Reproduce**
1. Have a character with associated sheet invited to a campaign.
2. From the "Cast" section of the Campaign choose "Edit Sheet"
3. Receive 404 error

**Expected behavior**
For the sheet of a PC invited and accepted to the campaign the character sheet should appear and be editable.

**Screenshots**
Youtube link for screen recording demonstrating this issue: [https://www.youtube.com/watch?v=p12NtrvWrYw](https://www.youtube.com/watch?v=p12NtrvWrYw)

**Comment by Kordishal** [comment]
The issue here is the button should not display. Giving a GM edit rights on a players sheet requires some extra steps.

Follow this [guide](https://www.worldanvil.com/w/creation/a/invite-characters-article). A community member created this guide.

In the not so distant future, this system will be reworked (Project Hercules) to just give the GM access rights instead of the current way.
