### ISSUE TITLE
World Name Locked

### ISSUE THREAD

**Issue by lmglegg** [worldanvil/worldanvil-bug-tracker#547]
**lmglegg**:

**Eos**:

**Create New World**: 

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
"Eos" was the name of a world I had in a previous account with World Anvil I deleted. When I try to build a new world with my new account using the same name, I get the 404 Error message page. If possible, I would like to use the name Eos again for my world. Thank you.

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by iamromeo** [comment]
Hello @lmglegg I am really sorry but as I am sure you can understand, although I am able to do this, I cannot use the development time for a free account, especially since the request itself is straddling somewhat the ToS. (Account duplication)

If you were a guild member that would be a different conversation. This is not a push to get you to subscribe, but I cannot use the time for things like that for people that do not support the platform. 

You can alternatively change your username or the name of the world - both will work
