### ISSUE TITLE
Content deletion

### ISSUE THREAD

**Issue by hawkandhartlee** [worldanvil/worldanvil-bug-tracker#569]
While editing in the manuscript function, The program deletes whole chunks of content.

This is understandably extremely frustrating. 

Please help us.

**Comment by Kordishal** [comment]
Hi, we can't really help you with this little information. Please come by the [Discord](https://worldanvil.com/discord) server for support. Manuscripts does not generally delete content by itself.

**Comment by hawkandhartlee** [comment]
Sorry for the lack of information. I was a bit frustrated, and failed to
properly communicate what is happening.

My partner and I are moving our manuscript from Dabble to World Anvil. As
we do so, we are proof reading our manuscript section by section with
Grammerly.
In the process, 2 sections delete after we add our content. To be more
specific:

1. We add the section to World Anvil.
2. After double checking our work, We move to the next section.
3. In the course of reviewing the chapter, we find that a section has no
content.

We have added the content back. However, when we leave that section, the
content is deleted again.
We have 2 sections, where content refuses to stay were we put it. You can
see how I became a bit frustrated, especially being in the middle of proof
reading. An activity that my writing partner and I already find to be a
chore worse than mowing the lawn with nothing more than nail clippers.

We came to World Anvil because your sight seems unmatched in the tools
you've created for world building. I really want to continue using your
service, so please feel free to contact me if you need anymore information.

-Hawk&Hartlee-

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by Kordishal** [comment]
Hi! No worries, it can frustrate when things do not work the way you expect them to. 

From the workflow you describe, I suspect that the issue is not that the sections are deleted, but are not saved. What I mean by that is that the auto-save is only triggered by any key pressed on the keyboard while the page is open. This would mean that if you copy & paste content with the context menu and then use the mouse to select Grammarly corrections, no key presses are made. As a result, the content is not saved.

To circumvent this issue, simply press any key on the keyboard after finishing applying Grammarly corrections to the section before moving on. When successfully saved the section a green badge will appear in the upper right corner.

If this does not resolve the issue, then it is possible that the copied content contains some encoding with which the system cannot save. Failure to save is unfortunately currently fairly silent in the manuscript feature. In this case make sure to paste without formatting (CTRL+SHIFT+P or via toolbar).
