### ISSUE TITLE
Categories Shuffle Randomly

### ISSUE THREAD

**Issue by Sockret** [worldanvil/worldanvil-bug-tracker#57]
**World Anvil Username**: Sockret
**Feature**: Categories

**Describe the Issue**
Whenever I sort my categories they somehow shuffle themselves in what seems to be a randomized manner. Doesn't make sense and it's really annoying.

**To Reproduce**
1. Go to Articles & Categories
2. Sort your Catergories in whatever way you wish
3. Click on View World
4. See them now being randomly sorted.

**Expected behavior**
I wanted them to stay in the way I have sorted them

**Screenshots**
<img width="960" alt="Alphabetical" src="https://user-images.githubusercontent.com/80486687/110851690-a68cce00-82b1-11eb-95cd-f7d34ca81597.png">
<img width="960" alt="Sorted" src="https://user-images.githubusercontent.com/80486687/110851701-ab518200-82b1-11eb-90ef-6f4a16312c13.png">

**Comment by Kordishal** [comment]
This is a known issue. The problem is that the categories after dropping are not actually saved where it visualizes. As a work-around make sure after drag & drop to press the reload (arrow circle) on the right of the category circles. If it happens and try again. If you can't get it to work try using the manual weight position option on the right after selecting the categories.

**Comment by iamromeo** [comment]
Check through the categories,There is a chance are that the ones that move have no weight on them. 
This is an issue that some older to the platform users experience
