### ISSUE TITLE
Footnote + Map Bug

### ISSUE THREAD

**Issue by LegitTeddyBears** [worldanvil/worldanvil-bug-tracker#572]
**LegitTeddyBears**:

**Eldria**:

**Embedded Maps**: 

**https://www.worldanvil.com/w/eldira-legitteddybears/a/li-e-location?preview=true** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
If I embed a map into a footnote of an article as to have the map below it.  I found I am unable to edit that footnote section anymore.  For example I wanted to remove the map the from page linked but the footnote section appears to be uneditable unless i doubleclick on the map reference and select the whole footnote.  This allows me to delete the text (but not write in or embed a new map) but upon saving and going back to the page the original map is still embedded.

**To Reproduce**
1. Go to 'Any article probably, design, the footnote section'
2. Click on 'paste a map's embed link'
3. Save the page
4. Refresh the page
5. Attempted to delete the embed tag

**Expected behavior**
Your article should be stuck with the embedded map forever

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by iamromeo** [comment]
Hey LegitTeddyBears! (love the username) 
The chances are that you are still using the WYSIWYG and using with it an advanced type of a tag (map with vars) 
In order to use any advanced functionality you need to use the advanced editor, "EUCLID"

You can change between editors here: 
https://www.worldanvil.com/dashboard/user/interface
