### ISSUE TITLE
Image uploads stall at 2MB (possibly just for new guild member)

### ISSUE THREAD

**Issue by CMAlbrecht** [worldanvil/worldanvil-bug-tracker#656]
Reported by:  Draigsffau, a.k.a. CMAlbrecht re. World of Serendia

As a new user who upgraded from Freeman to Master on my first day, I found that the uploads initiated either by dragging and dropping into the image manager or clicking on the drag and drop area to select a file *always* stalled somewhere around 2 MB (but not consistently *at* 2 MB) despite the fact that my uploads were supposedly limited to 10 MB; the upload would never complete. (Never, as in I waited 15 minutes or so after progress had ceased, just to be clear on the meaning of "never" in this context.)

When image uploading stalls, the observable symptom is that the upload progress bar stops moving and does not subsequently update.

I tried this at least 20 times on various different image files before hitting on the workaround of uploading the images using the "new map" interface (which works just fine, thank you).

Even though the 10MB guild member limit was clearly shown on the web page I was interacting with, my first guess is that the 2 MB Freeman limit was still being incorrectly imposed on the server side.

Image files considerably smaller than 2 MB (on the order of 150K) completed uploading as expected, convincing me that the underlying issue was indeed file size.

As a new guild member, I found this behavior quite frustrating.

**Comment by iamromeo** [comment]
Hello CMAlbrecht, just as a note using the map system to upload images, is going to be something will regret doing in the future so I would strongly suggest that you don't for your own good :) 

Now, this is a very odd one because 
a) I cannot replicate it and nobody else I asked across the world was able to. It is not related to your guild rank since that would have been presenting you with an actual error.
b) It is not a local network issue since obviously maps do work and you can upload large files like that

- Which browser are you using? 
- Do you have any settings on your firewall that might interfere with Javascript
- Do you have any options on your browser or limitations that might interfere with Javascript
- Have you noticed any instability on your local / extended network

**Comment by CMAlbrecht** [comment]
Dimitris,

I use the Firefox browser.
I have not set anything in the browser or on the router that would
interfere with javascript.  My local network is the Google mesh network,
though nearly all of my work is in the vicinity of the primary unit, so the
"meshness" isn't likely to be affecting my experience.
I did not notice any network instability.  In fact, prior to attempting to
upload via the image manager I had spent much of the day uploading maps
into my world without mishap.

And just as a note, the image I was trying hardest to upload was in fact a
map image, one sized to use as a "cover image" for the world.

Thank you for looking into this.

--Chris of Draigsffau

**Comment by iamromeo** [comment]
- Can you please give me a link to the image itself. 
- Did this occur for ALL files over a certain size (have you tried others)

**Comment by CMAlbrecht** [comment]
Sure! The image was [img:2744514]. I previously tried a larger image of
the same subject (4.33 MB vs. 2.21).  The smaller image which worked
without mishap was [img:2744508].

**Comment by Kordishal** [comment]
Hi. The image BBCode does not work. In general, most of the time when an upload does not work, it is in my experience some special / corrupted metadata that World Anvil cannot deal with.

You should be able to just re-export the original image with an image processing software such as Gimp. For best experience consider converting it to the WEBP format which is optimized for online use.
