### ISSUE TITLE
Map sidebar is broken by [col3] elements in world description

### ISSUE THREAD

**Issue by ShDrayker** [worldanvil/worldanvil-bug-tracker#667]
**World Anvil Username**: Drayker

**World / Campaign / RPG Character / Manuscript Title**: https://www.worldanvil.com/w/troupe-de-l-horizon-drayker

**Feature**: Map

**Related URLS** (To public & visible pages add screenshots otherwise): https://www.worldanvil.com/w/troupe-de-l-horizon-drayker/map/aaf51ab9-e25c-44c2-b9ec-2d41907d95df

**Describe the Issue**
World map is now a blank page (still visible in edit mode, with markers and all).
Funny enough, text from the homepage appears on the map page as broken script.

**Expected behavior**
Map showing !

**Screenshots**
![Homepage text showing on map as broken script](https://user-images.githubusercontent.com/82477852/140419375-22603f4b-e530-4e9f-b100-b28b55b68206.JPG)

**Comment by iamromeo** [comment]
Hello there :) 

It seems that you have an  unclosed tag in your world introduction which normally appears on the sidebar of your map that causes this issue - This is not a bug. :)

**Comment by ShDrayker** [comment]
Hi, tanks for your answer. Could you indacte where the unclosed tag you found is? Can't find it.

**Comment by Kordishal** [comment]
The issue is with [col3] elements.

The following text in the world description / introduction reproduces the issue:

```
[row][col3]TEST[/col3][col3]TEST[/col3][col3]TEST[/col3][/row]
```

I also noticed that [col][/col] is simply removed from the field when rendered in the world sidebar. I assume this has something to do with a change you did on how that sidebar is managed recently.

It appears to me that the world description / introduction currently just doesn't support advanced BBCode because of its use in the World Map.

In my opinion, it would be better to create a more robust solution for this and have a specific field which is used for the map sidebar with special rules instead of applying two rules to the same field depending on where it is used.

**Comment by iamromeo** [comment]
![image](https://user-images.githubusercontent.com/660175/142563804-da76ec7b-e365-48b5-9c05-84c08d56ecac.png)

I am sorry but I cannot reproduce this. 
May I ask, are you using Bootstrap 3 or Bootstrap 5?

**Comment by Kordishal** [comment]
Did you open a map? It works fine on the homepage. Pretty sure I tested in in BS5 only.

**Comment by Kordishal** [comment]
https://www.worldanvil.com/w/breaking-anvil-soullink/map/568e9560-7a2c-4c48-b990-5343306a151c
https://www.worldanvil.com/w/breaking-anvil-soullink

**Comment by MGatta** [comment]
Reporting that I also have this issue. I also have col3s in my world intro, which are properly closed and haven't created any issues up until today. I have never changed Bootstrap, so I assume I am in 3.
https://www.worldanvil.com/w/13-mgatta

**Comment by iamromeo** [comment]
@Kordishal in your example your map is private - I cannot access it.  (keep in mind for future reference) 

But found and fixed - there was a very strong catch-all filter being implemented there.
