### ISSUE TITLE
Manuscript Isn't Align in the middle

### ISSUE THREAD

**Issue by buckwell0** [worldanvil/worldanvil-bug-tracker#685]
**World Anvil Username**: buckwelles

**World / Campaign / RPG Character / Manuscript Title**: End Of Everything

**Feature**: Manuscript - World

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
Hi. I copy pasted my manuscript link into: Homepage - Custom Content - Full Width Column. But when I view my world, even if I'm chosing the middle column, the manuscript is showing in the left side. :(

**To Reproduce**

1. Go to World View -End Of Everything

**Expected behavior**
I would expect my manuscript showing in the presentation world homepage to be in the middle

**Screenshots**
![bug1](https://user-images.githubusercontent.com/84354328/141423988-3900ba25-046a-4afc-a2f0-0d0044b42b48.png)
![bug2](https://user-images.githubusercontent.com/84354328/141423993-e0602379-0d2a-4c62-9ad6-f05d3ab9a0d3.png)

**Comment by buckwell0** [comment]
here's my world homepage link to see what I mentioned.

https://www.worldanvil.com/w/end-of-everything-buckwelles

**Comment by Kordishal** [comment]
Hi this is not a bug in that sense, because the center BBCode can only affect text and not images. The generated cover is an image. This likely will only center the text on it which doesn't seem centered because it fills its space.

To resolve this either use the BBCode [concol][/concol] or three columns [row][col3][/col3][col3][manuscript][/col3][col3][/col3][/row]

However, at the moment there is a bug with the col3's on the world homepage for map sidebars. So until that is resolved use the first option (which likely won't work 100%).
