### ISSUE TITLE
Map Editor Not Loading Properly

### ISSUE THREAD

**Issue by ReginaRahimi** [worldanvil/worldanvil-bug-tracker#700]
**World Anvil Username**: CrookedTiesClub

**World / Campaign / RPG Character / Manuscript Title**: JahanTala

**Feature**: Maps

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
I spent a considerable amount of time in Presentation mode editing my map markers, but when I go back to the regular map editing page, neither the markers nor the map image display. My markers and their descriptions are listed under the marker tab, so the information is still there. Additionally, when I try to open the map in presentation mode again, the map image itself displays, but without any markers.

**To Reproduce**
1. Go to Dashboard --> Maps
2. Click on 'Edit' for my map JahanTala
3. See error - blank editing screen with no image or markers

**Expected behavior**
Previously when I've clicked the edit button, the map displayed the the few markers I had placed at the time (no more than 5 iirc)

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window
![screenshot-www worldanvil com-2021 11 20-10_35_21](https://user-images.githubusercontent.com/33848701/142734012-5bf67a2a-8448-4e65-974a-f5e839112e5a.png)
!

**Comment by Kordishal** [comment]
This sometimes happens when there is an issue with the markers. Problems can be related to the description or title text of the markers. You should be able to resolve this by recreating the last view markers that you have created.

To give you further help with this I would need access to the map or at least see it. It would be easiest to discuss further on Discord: 

https://worldanvil.com/discord

You can find me on Discord as SoulLink#3294 or otherwise just ask in the #help channel

**Comment by ReginaRahimi** [comment]
Thank you!! There was a character used in Arabic transliteration that the
system clearly didn't like. I changed that and everything resolved. Thanks
again!
