### ISSUE TITLE
Page jumps around when trying to arrange articles

### ISSUE THREAD

**Issue by azelira1522** [worldanvil/worldanvil-bug-tracker#723]
**World Anvil Username**: azelira

**World / Campaign / RPG Character / Manuscript Title**: The Shattered Isles

**Feature**: Articles & Categories

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
When trying to rearrange articles using the "Arrange" button, the page jumps around as soon as you select the button so that you can't actually move the article where you want to. I was trying to put my articles in alphabetical order, and the only way I was able to finally get it where I wanted to was to zoom out the page to about 50% so I could see almost my entire list. It's a bit complicated to explain, so I'll use the actual example of what I was attempting. I have a category called "Races" with each D&D 5E race as its own category. I was trying to move the "Kenku" article from between "Minotaur" and "Orc" to between "Kalashtar" and "Kobold". I try dragging it up the page, but since the page doesn't automatically scroll, I drag Kenku as high as I can and then scroll up so Kenku is now at the bottom of the page. This seemed to work, but I accidentally moved Kenku too high up in the order. So I try to drag Kenku downward, and that was where the problem started happening. I would align the page so "Kenku" is at the top, but as soon as I tried to drag it downward, the page jumped up so Kenku was now at the bottom of the page instead (so obviously I couldn't continue to drag it downward, only up). It happened very sporadically, and I'm not 100% sure what was actually happening each time, but basically between the page not just scrolling automatically when I drag, and the page jumping around randomly, I had basically zero control over arranging my articles. 

**To Reproduce**
1. Go to 'Articles & Categories'
2. Click on a category to show its articles
3. Scroll down to N/A

**Expected behavior**
I would expect that when you click and hold "Arrange" to drag an article, the page would scroll automatically as you drag it up and down, rather than jumping to a random place and staying there. Or, at the very least, the page would stay still when trying to drag an article, so I can drag and drop, scroll, and repeat until I get the article where it needs to be.

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by iamromeo** [comment]
I am sorry @azelira I cannot reproduce this and neither any of the 4 people that tested it could. If you are having issues with a very long list of either articles or categories, you can always use the right sidebar to set an article under a category. 

That honestly sounds like a browser specific behaviour but I cannot be sure.

**Comment by Kordishal** [comment]
This happens when the Articles & Categories page is scrolled down. When selecting the arrange button, the Browse by Categories section is collapsed. This causes the view port to resize and the screen to "jump".

Which is why zooming out resolves the issue. Pre-collapsing the Browse by Categories section before arranging reduces the effect as well.

I've reported this before and back then you said you can't change it as this is browser behaviour. The easiest "fix" would be to not collapse the Browse by Categories. As this is an usability feature to prevent people from trying to use that button to move them to a different category, you could instead just gray out / disable that section to visually make it clear that's not its use.

Alternatively, find a way that the collapsing does not resize the page height, which then causes the jump.

**Comment by iamromeo** [comment]
@Kordishal I have read your explanation 3 times and I am still lost, can you please, when you have the time reach out on Discord to take me through this?

**Comment by iamromeo** [comment]
With the help of @Kordishal I have replicated the issue. It is an edge case but it is one that can be tackled so - I will be actioning this today

**Comment by iamromeo** [comment]
All fixed
