### ISSUE TITLE
Slow typing

### ISSUE THREAD

**Issue by TheArthurianKing6** [worldanvil/worldanvil-bug-tracker#738]
King@rthur:

Daearun:

Slow typing: 

Describe the Issue:
Hello reader
Whenever I am editing one of my articles in world anvil, I have to wait for the words to load (They take an extra 30 seconds to 2 minutes to load in). On other typing platforms on this PC, the typing is normal.

Expected behavior:
I would expect the typing to happen almost or at the same time I press the keys

Thankyou for your time, I hope this issue can be fixed

**Comment by Kordishal** [comment]
I've elaborated on Discord, but to reiterate for documentation:

This is usually caused by browser extensions such as password managers, spellcheckers or adblocks. To test whether this is the case try to see if the issue presists in a private or incognito window. There extensions are disabled. If this does resolve the issue the norrow than the offending extension and deactivate it. 

And on a sidenote: I've deleted the email address from your post. This is a public board which is crawled by bots that collect personal information. Communication happens through comments.
