### ISSUE TITLE
Font Awesome not loading into buttons

### ISSUE THREAD

**Issue by atp1o2** [worldanvil/worldanvil-bug-tracker#755]
StrongestToaster

/help/:1 Access to script at 'https://kit.fontawesome.com/8ad07c26d8.js' from origin 'https://www.worldanvil.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

This is preventing the icons to show up in the buttons 

![image](https://user-images.githubusercontent.com/11875611/146214252-2f3fe908-7205-4ed1-a0da-67563827e879.png)

This randomly happened on PC Chrome. It's still working fine on iOS Chrome. Any ideas on how to fix?

**Comment by Xuroth** [comment]
This is due to an issue with FontAwesome (a third-party that makes the icons and hosts them). There is currently a widespread issue affecting many websites (which does not affect us, aside from the icons displaying). Once they get things smooth on their end, everything will automatically show again!
