### ISSUE TITLE
Cannot creat map for world 

### ISSUE THREAD

**Issue by OrlexDarksoul** [worldanvil/worldanvil-bug-tracker#837]
![Capture](https://user-images.githubusercontent.com/98314927/150761885-2f05ea0d-7e9d-4105-a500-3ac91b8b1023.PNG)
**World Anvil Username**: Orlex

I try to create a world named Overworld and the I see this...

1. Go to create map 
2. Click on map name 
3. Wright Overworld

After you wright the world's name you'll see a Dragon with the number 404 and a text on it.

**Comment by Kordishal** [comment]
I cannot reproduce this issue with the steps provided.

Are you adding an image to the map creation? Are you adding a description? Do you mean you write Overworld in the TITLE field? Or what you mean with Click on map name?

My guess would be that the issue is related to the map image. Please come to the Discord as it is easier to give support there than here.

[Click here for Discord Server Invide](https://worldanvil.com/discord)
