### ISSUE TITLE
Cannot delete world with the same name

### ISSUE THREAD

**Issue by gn00me** [worldanvil/worldanvil-bug-tracker#853]
**World Anvil Username**: gn000me

**World / Campaign / RPG Character / Manuscript Title**: -

**Feature**: New World

**Related URLS** (To public & visible pages add screenshots otherwise): https://www.worldanvil.com/world/new

**Describe the Issue**
This is a continuation of #635 bug, since it was not resolved, the bug is still there.
"When I try to create a new world, I have an error message "You have no more world slots available :(". I've created a 2 worlds, but deleted one to create a new one, so I only have 1 world on a free account."

**To Reproduce**
1. Go to 'Worlds & Heroes'
2. Click on '+ New World'
3. -
4. See error 'You have no more world slots available :('

**Expected behavior**
Creation of the New World

**Screenshots**
![137626813-38959458-ae00-4207-98dd-23abadd6e38f](https://user-images.githubusercontent.com/3670722/151935322-a8214964-0942-4ce8-bd52-005aec2369d8.jpg)

**Comment by iamromeo** [comment]
Hello @gn00me  You already have 2 worlds on your account, both named Lunae Lumen

**Comment by gn00me** [comment]
Hi @iamromeo. Cool, cool, except I don't. I've deleted one of those (I'm attaching the pritsceen with the current stage of the worlds). Please take a look at the previous issue #635. So something went wrong with deleting, could you please solve this issue?
![Capture](https://user-images.githubusercontent.com/3670722/152104360-aa726da8-1cce-4534-b83a-f825d10d73b1.JPG)

**Comment by Kordishal** [comment]
Your screenshot proves that you have two worlds. The active world no longer appears in the SWITCH TO list. So the issue appears to be that you can't delete them, potentially because they have the same name.

**Comment by Kordishal** [comment]
Ah wait never mind. It appears that I was wrong. There should be two worlds in the list.

When I create a new world I cannot name it the same as an existing world. Did you rename one of these worlds after the fact?

@Dimitris: I just tested this: 

I created a world with name "Test World".
I tried to create a second world with name "Test World" -> leads to a 404 page and does not create a world (this should of course instead tell the user why you can't make a world with the same name...)
I then created a world with name "Test World 2" -> this created a second world.
I then went to rename "Test World 2" to "Test World". -> this lead to a 404 page as expected (and should really again tell the user that this isn't possible).

However, after reloading and switching to "Test World", the "Test World 2" has now disappeared. So even though the renaming caused a 404 error it still somehow changed the name and I can no longer access Test World 2. But I probably now have two worlds with Test World as a name which confuses all the systems as it should not be possible.

So you need to fix the renaming bug at least and then help gn000me delete one of their worlds as they can't do it by themselves since the interface doesn't allow it.

On my test account I deleted the original Test World and now my account is basically unusable. The original "Test World" had a campaign associated with it but I could still delete it. The campaign can now no longer be activated properly as it doesn't have a world.

The second "Test World" which was originally "Test World 2" is shown in the list of SWITCH TO, but when I switch to it the dashboard is just white and does not load properly. 

However, after a few more reloads it appears now that Test World 2 is back!? and I can activate it. In return the campaign is gone. And when I load the RPG characters which were part of that campaign they look like this: 
![image](https://user-images.githubusercontent.com/14262536/152139714-a4004d31-ae9b-4a37-9986-ff4a38804a21.png)

**Comment by Kordishal** [comment]
I think some of the issue resolved themselves after I activated a world where the test account is a writer.

**Comment by gn00me** [comment]
Hi @Kordishal.
SO the order was like this:
I've created two different worlds (with a two different names). Then I've deleted Lunae Lumen world and since then can't create any new world. Few days ago I've changed the name from Age of Raven name to the Lunae Lumen name.

**Comment by gn00me** [comment]
It didn't.

**Comment by iamromeo** [comment]
Depending on when @iamromeo is trying to access it from it might simply not have refreshed the cache. The dashboard list is immediate the sidebar is  not

**Comment by gn00me** [comment]
@iamromeo I was able to find this world and delete it, now I can add another one, there's no longer this error message. Thanks for you suggestion, please close this ticket
