### ISSUE TITLE
Manuscripts: Text font size does not stay set to that size

### ISSUE THREAD

**Issue by shyredfox** [worldanvil/worldanvil-bug-tracker#867]
**World Anvil Username**: shyredfox

**World / Campaign / RPG Character / Manuscript Title**: The Bard's Magic (and every manuscript)

**Feature**: Text font size

**Related URLS** (To public & visible pages add screenshots otherwise): See screenshots. This is only on the writing side of the manuscripts.

**Describe the Issue**
I have the font size set to 14, nice and big so I can read it without squinting. But it does not default to this size in two cases.
- when I write in a new section of the manuscript
- When leaving the document and coming back to it, then clicking in an area with a blank line gives a smaller text size again.

While this isn't a deal breaker, it's bad for work flow.

The font (name of the font) I set it to is consistent. It seems to be JUST the text size.

Anyhoo, just reporting. Thanks for taking a look at it.

**To Reproduce**
1. Set your font size for a manuscript big like 14 or bigger
2. Make a new section. 
3. type a bit. Then see if manually setting the font size makes it bigger.

Version 2
1. in your manuscript section, make a new line
2. leave the page and come back to it. Type where there is the new line. The font is smaller again. 

**Expected behavior**
The font size should be consistent. 

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!
Here I have the font size set for the manuscript - ![Screenshot_100](https://user-images.githubusercontent.com/59369948/153255767-c4b92924-ac8e-4712-872e-c5024e4f1e36.png)

This is what the font size should look like. ![Screenshot_101 - it should be this size alwyas](https://user-images.githubusercontent.com/59369948/153266231-f23910a1-3b21-4efa-8cb8-65bbb20ae403.png)

Here is a new, untouched section of the manuscript. The font size is not correct. ![Screenshot_101 - new section much smaller text](https://user-images.githubusercontent.com/59369948/153266258-b2c51d7b-1cdb-4262-910b-5711e89259e7.png)

Setting the font size manually ![Screenshot_101 - setting the font size](https://user-images.githubusercontent.com/59369948/153266270-b6a3b75a-c84c-49a3-a594-667c54d73bb2.png)

Here is the blank line - it's not the right size. (see next screenshot for text in that area) ![Screenshot_101 - smaller text on leaving section and coming back to put cursor in a blank line](https://user-images.githubusercontent.com/59369948/153266278-18419bc9-9d62-412b-94b8-f96712cabc4d.png)

After setting it manually, Here is the same thing - but I started typing. Text is not right size. ![Screenshot_101 - smaller text on leaving section and coming back to put cursor in a blank line 2](https://user-images.githubusercontent.com/59369948/153266294-0edfef02-8599-47ce-abbc-548c5a1748f3.png)

**Comment by shyredfox** [comment]
The first screen shot is where that is supposedly set for the manuscript. But it doesn't stay set to 14pt.

**Comment by shyredfox** [comment]
Did there used to be a way to set a default size for fonts in manuscripts and articles? I can't find that in settings now.  

Anyhoo, 14 pt shows up set for every manuscript I have, but does not seem to be the default when I go into a section to type. Hopefully that makes sense.

**Comment by Kordishal** [comment]
Hi ShyRedFox!

This has been bothering me as well so I finally took the time to study this a bit and found the issue:

After changing a setting in the default interface menu it is necessary to reload the manuscript for the settings to be applied to *existing* scenes or to *new* scenes!

... and of course right after writing this down I finally noticed that this is actually documented right there on the menu. I've never seen this before :face_with_head_bandage: 

Furthermore some of the settings are a bit different:

![image](https://user-images.githubusercontent.com/14262536/153448829-55e1e4ae-d84c-4e8f-b1dd-8c70d03ad2c9.png)

Generally speaking it is important to consider the placeholder values present.

- The Font Size setting does **NOT** need a unit supplied. The application adds **px** to the value automatically. So since you wrote 14pt it can't work.
- All of the paragraph settings on the other hand need units for them to work. That seems a bit sub optimal, though technically the placeholder values indicate this correctly. 
- **The Paragraph Bottom Padding setting does not seem to work**. No matter what kind of a value I added to it nothing changed.
- In order to have no paragraph padding it is required to remove margins as well. This can be done with CSS EXTRA RULES, but seems a bit weird.


For Dimitris:

I could not get the PARAGRAPH BOTTOM PADDING setting to apply to the paragraphs in the settings after reloading. I can't see the value anywhere and I've tried many different ones.

**Comment by shyredfox** [comment]
Thank you, Kordishal!

Yes, the units and the refresh totally threw me. And that works. Uffdah! That was not clear for me.

To have a note with the FONT SIZE to say something like (don't specify units, it uses px) would help. (Yes, the placeholder values *should* have hit me over the head. But everything else specifies units.*

In dark mode, bold never stands out as well as it does in light mode. Could we have "Once you are done, refresh the page so the settings can take effect." be in yellow or something?

**Comment by iamromeo** [comment]
Please do not reopen before consulting with me @Kordishal

**Comment by iamromeo** [comment]
@Kordishal I can confirm the **paragraph bottom padding** not working and I found out why 
the creator of the pluging changed padding-bottom to a new type element called margin-block-end  (never seen this before) 

I will address this.

**Comment by iamromeo** [comment]
Paragraph bottom padding also fixed it will be deployed today
