### ISSUE TITLE
Manuscripts Autosave Doesn't Trigger After Media Insert

### ISSUE THREAD

**Issue by FibroJedi** [worldanvil/worldanvil-bug-tracker#873]
**World Anvil Username**: FibroJedi

**World / Campaign / RPG Character / Manuscript Title**: Qal'ath

**Feature**:  Manuscripts

**Related URLs** (To public & visible pages add screenshots otherwise):
I don't have any public manuscripts yet and the issue is not relevant to normal WorldAnvil Articles.

**Describe the Issue**
I thought the inline media insert wasn't working until I figured out what the issue was. Unlike typing, where the autosave happens when typing is paused, this does _not_ trigger on media insert. This led to me inserting it multiple times - heading to preview only for it not to be there _nor_ in the word processor when I switched back to the editing tab.

**To Reproduce**
Do not type any letters/words during this process

1. Go to Manuscripts
2. Edit a Manuscript 
3. Insert a media file
4. Immediately go to Preview (item was not there for me)
5. Return to the editor (where the media insert had also vanished for me)

**Expected behavior**
The autosave to have run after media insertion, such that going to preview and back again retains the image regardless of whether I have typed some words or not.

**Screenshots**
I don't think these are needed but let me know if that assumption is wrong!

**Comment by iamromeo** [comment]
I am not what you mean by inserting media, but Manuscripts, do not have the functionality to do so. This is not part of the featureset UNLESS you are using the special section type for images OR the Category > Rich Media URL

**Comment by FibroJedi** [comment]
Sorry for the late reply, but I'll try and explain quickly now and then
follow up with screenshots, tomorrow hopefully.

In manuscripts you *can* insert an image (which is what I mean by "media").
I only said "media" because I believe that's what the menu item says.

So, when I insert an image, the autosave doesn't trigger like it does after
a keypress.

I don't know if that's clearer?
Thanks!

**Comment by Kordishal** [comment]
They are talking about this Dimitris:

![image](https://user-images.githubusercontent.com/14262536/154819299-352eecff-33b3-4f1e-aa03-ab68d896f2fa.png)

It can be accessed via the second row toolbar icon: 
![image](https://user-images.githubusercontent.com/14262536/154819315-7b1d62a5-7f54-42ec-ba6f-d737be3652ee.png)

It can be used to add videos with it. Not images.

But yeah this is essentially because mouse clicks are not registered by the auto-save. There might be a change for this in the future, but it isn't high priority.
