### ISSUE TITLE
Images I have embedded below text in my articles pop out of speech bubbles. 

### ISSUE THREAD

**Issue by Grimmibo** [worldanvil/worldanvil-bug-tracker#942]
World Anvil Username: GRIMMBO

World / Campaign / RPG Character / Manuscript Title: VALADAR

Feature: Image embedding/ speech bubbles when hovering over linked articles.

Describe the Issue: Sorry for the repost, I didn't see the responses to my last post in time and it was closed. I will have my notifications on and respond as soon as I can. I keep having this problem where if I hover over an article name in view mode, if it has an image embedded below the text, the first time I hover over it the image sticks out of the speech bubble thing that pops up, making it so that if I try to click on said link, it just directs me to a page of the image by itself. Is there a way to fix that? Right now I have to hover over the link twice to get the image to stay in the speech bubble and allow me to click on the article I was hovering over, which is annoying.

To Reproduce

Go to any article with a linked article alongside the sidebar.
Hover over a linked/related article within the article clicked on.
See error
Expected behavior
I just want the image to not overlap with the speech bubble the first time I hover over it.

Screenshots
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!
![Image_overlap_problem](https://user-images.githubusercontent.com/101070225/160036302-c9d16ef8-34f0-434f-8c1e-3823ffe22b3b.png)

**Comment by Kordishal** [comment]
For the future you can just respond on the closed ticket and we can re-open it when new information comes up.

Can you create an example with a public article in a public world and then put a link? The reason the old ticket was closed is because Dimitris was unable to reproduce this issue on his end. Seeing an example might help figure this out.

In addition it might be useful to have the BBCode or at least a screenshot of the EDIN ARTURUS article. (of the main content).

**Comment by Kordishal** [comment]
related to #898

**Comment by Grimmibo** [comment]
Why was this closed? Would you prefer I continue in my previous entry?
