### ISSUE TITLE
PDF viewer not working as expected.

### ISSUE THREAD

**Issue by FalconXray** [worldanvil/worldanvil-bug-tracker#956]
**World Anvil Username**:  FalconX

**World / Campaign / RPG Character / Manuscript Title**: WATER PLANET X25 / Earth 2023

**Feature**: [PDF:url||]

**Related URLS** (To public & visible pages add screenshots otherwise):
These two do not work as far as i know
https://www.worldanvil.com/w/water-planet-x25-falconx/a/commerce-act---pdf-through-dropbox-document?preview=true?
https://www.worldanvil.com/w/water-planet-x25-falconx/a/commerce-act-through-google-pdf-document?preview=true?

This one half works.  
https://www.worldanvil.com/w/earth3A-2023-falconx/a/france-article?preview=true?

Just wondering if the uploading of the pdf is so slow that it just shows a grey rectangle placeholder.

I understand that PDF's do take up room.  Maybe when they are uploaded they could be put through a file squiser so that they are as small as possible without destroying the quality.  

**Describe the Issue**
I have had mixed results with the PDF viewer files from external websites that seem to work ok given time and bandwith.  HAve not been able to link through dropbox or google drive

I do use Safari on a Mac

**To Reproduce**
Steps to reproduce the behaviour:
Go to the urls I have given and view the result

**Expected behaviour**

**Screenshots**
![Screen Shot 2022-04-01 at 6 06 33 pm](https://user-images.githubusercontent.com/102790891/161222392-d96d75b1-be2f-466a-9403-de8097e1b601.png)

**Comment by Kordishal** [comment]
All World Anvil does is embed the external PDF. Any issues with speed or quality are because of the service you've used or your connection.

World Anvil can't change the PDF for you as it does not know about it at all. You should optimize the PDF yourself if it is too large. Not sure what kind of possibilities there are.

As for your examples: The half-working one is private so I can't check the content.

The Dropbox and Google Drive links do not work, because these are not PDF links. The iframe needs a link that actually ends in .pdf (or more specifically a link that just returns a pdf with the proper metadata) and not just a link that leads to the file.
