### ISSUE TITLE
Inconsistent formatting for Meta subheaders

### ISSUE THREAD

**Issue by schizoidnightmares** [worldanvil/worldanvil-bug-tracker#968]
**World Anvil Username**: schizoidnightmares

**World / Campaign / RPG Character / Manuscript Title**: The Absurd Realms

**Feature**: Meta

**Related URLS** (To public & visible pages add screenshots otherwise): https://www.worldanvil.com/w/the-absurd-realms-schizoidnightmares/meta

**Describe the Issue**
Unlike the other headers, subheaders do not appear under Focus. Instead the paragraphs appear without their subheaders and do not seem spaced appropriately.

**To Reproduce**
1. Navigate to https://www.worldanvil.com/world/meta
2. Go to the Focus tab
3. Fill out the first and second focus point text boxes
4. Save changes
5. Click on "View World Meta"
6. Scroll down as needed to the header "Focus"
7. See how there are no subheaders (e.g. divisions) between the text entered for the first and second focus point

**Expected behavior**
Subheaders should appear like they do for the other sections I filled out (e.g. Scope, Theme, etc.)

**Notes**
May want to see if this problem is present under the other sections that I have yet to fill out (e.g. Drama, Scene etc.).

**Comment by Kordishal** [comment]
That is on purpose so that you can set your own headers. Foci, Drama and Scenes are likely to need their own custom headers unlike the other specific questions. 

So instead of having headers Focus 1, Focus 2 etc. you can actually have the title of the focus in the header and then elaborate on it. Use [h2] headings.
