### ISSUE TITLE
Exporting my world always says failed

### ISSUE THREAD

**Issue by lequient** [worldanvil/worldanvil-bug-tracker#976]
**World Anvil Username**:

**World / Campaign / RPG Character / Manuscript Title**:

**Feature**: 

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
A clear and concise description of what the issue is.

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by Kordishal** [comment]
What is the error message?

**Comment by lequient** [comment]
its saying job failed

**Comment by Kordishal** [comment]
I need the full sentence to figure out what is wrong. And I'll also probably need your help otherwise to figure it out. Can you contact me on the World Anvil Discord Server?

https://worldanvil.com/discord

SoulLink#3294

**Comment by lequient** [comment]
the entire line is, Job Failed:pywaclient.exceptions.AccessForbidden:article/9791092c-1c13-4c46-8f23-c9a29d24513a     I dont have discord but im going to download it
    On Monday, April 11, 2022, 02:39:46 AM EDT, Jonas Waeber ***@***.***> wrote:  
 
 


I need the full sentence to figure out what is wrong. And I'll also probably need your help otherwise to figure it out. Can you contact me on the World Anvil Discord Server?

https://worldanvil.com/discord

SoulLink#3294

**Comment by iamromeo** [comment]
@lequient @Kordishal  (SoulLink) has asked you to message them in order for him to help you - can you please do so, so we can find a solution for you? We cannot help you if you do not help us identify your issue.

**Comment by lequient** [comment]
After I try to export my world, I wait a couple of minutes, then a line that says 
Job Failed: pywaclient.exceptions.AccessForbidden: article/9791092c-1c13-4c46-8f23-c9a29d24513a

**Comment by lequient** [comment]
![Uploading IMG_20220409_155243120.jpg…]()

**Comment by lequient** [comment]
![Uploading IMG_20220409_155217557.jpg…]()

**Comment by Kordishal** [comment]
Hi! Yes I am aware, but this does not tell me enough. There is a bug that causes this to happen. However, in order to track it down we need to reproduce this same issue.

This is only possible with having an authentication token from you so that I can test this thing. As this is a public board you cannot share this here. Which is why communication over Discord is necessary.

I suppose alternatively you can also email Dimitris with the token so he can hand it over to me for me to test.

Once I'm done with the testing I can inform you so you can once again delete the token.

**Comment by lequient** [comment]
i will email dimitris the token

**Comment by Kordishal** [comment]
Account was deleted. So no longer possible to test as far as I can tell.
