### ISSUE TITLE
Adding new article link to template prompt requires reload after adding them before existing articles can be selected again.

### ISSUE THREAD

**Issue by AntLorien** [worldanvil/worldanvil-bug-tracker#981]
**AntLorien**:

**World: Perrin**:

**Template Specifics**: 

**Entry Locked**
After using the "create a new article and link it" button, that next entry locks the user out of entering more arguments.

**To Reproduce**
1. Go to Races
2. Click on Template Specifics
3. Scroll down to a "create a new article and link it" button
4. Enter in new article name
5. Hit Enter
6. See error

**Expected behavior**
Upon refreshing the webpage, you can add more items to each entry, but repeating the behavior once again locks the user out. The only way to enter more without refreshing is hit the button again, which just takes you back to step 4.
**Screenshots**
![image](https://user-images.githubusercontent.com/58447688/163237684-bb33a10f-18a0-49fa-972e-453c3f698e60.png)

**Comment by Kordishal** [comment]
I am not sure I understand what you mean?

When you clock the "Create new article and link it" it adds an input field and a Create & Link button. Then you add a name and click the button it creates the article and links it like the SIREN in your image.

Then you can repeat this by clicking the `Create new article and link it` button again and so on. Each time an article is created and linked. Each newly created article is listed under where the siren is listed.

Then after a reload it returns to the list of ethnicities again.

And after writing all that out: Do you mean that it should return directly to the dropdown menu after creating a new article instead of just displaying it like the in the image? So that you can go back to adding more existing articles without having to reload the page?

**Comment by iamromeo** [comment]
This is a known and recorded issue in the pipeline

**Comment by iamromeo** [comment]
Thank you for reporting and for your help
