### ISSUE TITLE
D&D Importert fails to import specific character.

### ISSUE THREAD

**Issue by DSewell83** [worldanvil/worldanvil-bug-tracker#985]
**World Anvil Username**:

**World / Campaign / RPG Character / Manuscript Title**:

**Feature**: 

**Related URLS** (To public & visible pages add screenshots otherwise):

**Describe the Issue**
A clear and concise description of what the issue is.

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. You can add screenshots by drag & drop into this window!

**Comment by Kordishal** [comment]
Hi, your description is very unclear what is actually going on. Are you referring to the D&D Beyond character importer? If yes then please post the identifier of the character you are trying to import.

Otherwise further explain what you mean or where you are encountering this issue. Please fill in the actual body of the issue and answer all the prompts. Otherwise there is nothing that can be done to fix this issue.

You can either answer via the email or edit your original post and add all the information necessary.

**Comment by DSewell83** [comment]
I created new stat block page, clicked big red button, copy/pasted numeric character id, clicked submit button, red error box top right corner reads 500: Importer error.

71296127<https://www.dndbeyond.com/characters/71296127>

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by iamromeo** [comment]
Hello there - we will have a look but, can you please give us your WA username please?

**Comment by FroBoyX** [comment]
> I created new stat block page, clicked big red button, copy/pasted numeric character id, clicked submit button, red error box top right corner reads 500: Importer error. Character ID: 71296127 URL: https://www.dndbeyond.com/characters/71296127

Thank you for sharing the character, the first issue is that the character appears to be using a custom *Background* that has no *name* which leads to an error. Diagnosing any others with the character.

**Comment by FroBoyX** [comment]
_The Ivory Queen Denari Havensong's Body Double Bellona_ now imports, there has been a clause added to the importer to pass an empty string in the event that **D&D:B** returns a character with no *Background Name*.

You should now be able to import @DSewell83. Once you confirm the issue will be considered closed.

**Comment by iamromeo** [comment]
Closed due to no response from the user
